#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
E2E_DIR="$ROOT_DIR/e2e_watch"
ENV_FILE="$E2E_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
  set +x
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

REQUEST_ID="${REQUEST_ID:-${RELEASE_REQUEST_ID:-$(uuidgen 2>/dev/null || openssl rand -hex 16)}}"
RUN_ID="${RUN_ID:-run_$(date +%Y%m%d_%H%M%S)_$(printf '%s' "$REQUEST_ID" | tr -d '-' | cut -c1-8)}"
OUT_ROOT="$ROOT_DIR/output/e2e_watch"
RUN_DIR="$OUT_ROOT/$RUN_ID"
LOG_DIR="$RUN_DIR/logs"
SHOT_DIR="$RUN_DIR/screenshots"
VIDEO_DIR="$RUN_DIR/videos"
JUNIT_DIR="$RUN_DIR/junit"
PID_DIR="$RUN_DIR/pids"

mkdir -p "$LOG_DIR" "$SHOT_DIR" "$VIDEO_DIR" "$JUNIT_DIR" "$PID_DIR"

APP_PACKAGE="${APP_PACKAGE:-com.company.internalerp}"
APP_ACTIVITY="${APP_ACTIVITY:-.MainActivity}"
APK_VARIANT="${APK_VARIANT:-debug}"
APK_PATH_OVERRIDE="${APK_PATH_OVERRIDE:-}"
APPIUM_PORT="${APPIUM_PORT:-4723}"
APPIUM_LOG_LEVEL="${APPIUM_LOG_LEVEL:-info}"
WATCH_MODE="${WATCH_MODE:-1}"
KEEP_EMULATOR_OPEN="${KEEP_EMULATOR_OPEN:-1}"
STEP_DELAY_MS="${STEP_DELAY_MS:-600}"
RUN_TIMEOUT_SECONDS="${RUN_TIMEOUT_SECONDS:-300}"
RECORD_VIDEO="${RECORD_VIDEO:-1}"
MAX_VIDEO_SECONDS="${MAX_VIDEO_SECONDS:-180}"
SCREENSHOT_ON_EACH_STEP="${SCREENSHOT_ON_EACH_STEP:-1}"
WIPE_DATA="${WIPE_DATA:-0}"
BASE_URL="${BASE_URL:-http://127.0.0.1}"
BASE_PROJECT="${BASE_PROJECT:-ERP_RMI_SOFULL}"
TARGET_ENV="${TARGET_ENV:-local}"

BASE_PROJECT="/${BASE_PROJECT#/}"
BASE_PROJECT="${BASE_PROJECT%/}"
BASE_URL_PROJECT="${BASE_URL%/}${BASE_PROJECT}/"
MOBILE_BASE_URL_DEBUG="${MOBILE_BASE_URL_DEBUG:-${BASE_URL%/}${BASE_PROJECT}/api/v1/mobile/}"

AVD_NAME="${AVD_NAME:-ERP_WATCH_API_30}"
AVD_API_LEVEL="${AVD_API_LEVEL:-30}"
AVD_ABI="${AVD_ABI:-x86_64}"
AVD_DEVICE_PROFILE="${AVD_DEVICE_PROFILE:-pixel_4}"
AVD_SYSTEM_IMAGE="${AVD_SYSTEM_IMAGE:-system-images;android-30;google_apis;x86_64}"

if [[ -z "${ANDROID_HOME:-}" ]]; then
  export ANDROID_HOME="${ANDROID_SDK_ROOT:-/usr/local/share/android-commandlinetools}"
fi
if [[ -z "${ANDROID_SDK_ROOT:-}" ]]; then
  export ANDROID_SDK_ROOT="$ANDROID_HOME"
fi
export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"

MASKED_ROOT='[WORKDIR]'
mask_path() {
  printf '%s' "${1//$ROOT_DIR/$MASKED_ROOT}"
}

write_env_snapshot() {
  cat > "$RUN_DIR/.runtime.env" <<EOF
REQUEST_ID=$REQUEST_ID
RUN_ID=$RUN_ID
APP_PACKAGE=$APP_PACKAGE
APP_ACTIVITY=$APP_ACTIVITY
APK_VARIANT=$APK_VARIANT
APPIUM_PORT=$APPIUM_PORT
WATCH_MODE=$WATCH_MODE
KEEP_EMULATOR_OPEN=$KEEP_EMULATOR_OPEN
STEP_DELAY_MS=$STEP_DELAY_MS
RUN_TIMEOUT_SECONDS=$RUN_TIMEOUT_SECONDS
RECORD_VIDEO=$RECORD_VIDEO
MAX_VIDEO_SECONDS=$MAX_VIDEO_SECONDS
SCREENSHOT_ON_EACH_STEP=$SCREENSHOT_ON_EACH_STEP
BASE_URL=$BASE_URL
BASE_PROJECT=$BASE_PROJECT
BASE_URL_PROJECT=$BASE_URL_PROJECT
MOBILE_BASE_URL_DEBUG=$MOBILE_BASE_URL_DEBUG
TARGET_ENV=$TARGET_ENV
AVD_NAME=$AVD_NAME
AVD_API_LEVEL=$AVD_API_LEVEL
AVD_ABI=$AVD_ABI
AVD_SYSTEM_IMAGE=$AVD_SYSTEM_IMAGE
EOF
}
