module.exports = {
  loginUsername: '~login_username',
  loginPassword: '~login_password',
  loginUsernameInput: 'android=new UiSelector().className("android.widget.EditText").instance(0)',
  loginPasswordInput: 'android=new UiSelector().className("android.widget.EditText").instance(1)',
  loginSubmit: '~login_submit',
  dashboardRoot: '~dashboard_root',
  navSales: '~nav_sales',
  navPurchases: '~nav_purchases',
  navStock: '~nav_stock',
  navChat: '~nav_chat',
  tasksSearch: '~tasks_search',
  tasksFilterAll: '~tasks_filter_all',
  tasksFilterPending: '~tasks_filter_pending',
  tasksFilterFailed: '~tasks_filter_failed',
  tasksFilterSent: '~tasks_filter_sent',
  taskRetryButton: '~task_retry_button',
  syncNowButton: '~sync_now_button',
  dashboardSyncHealthCard: '~dashboard_sync_health_card',
  dashboardKpiSales: '~dashboard_kpi_tile_sales_do',
  listFirstItem: '~list_first_item',
  detailHeader: '~detail_header',
  chatMessageInput: '~chat_message_input',
  chatSendButton: '~chat_send_button',
  logoutButton: '~logout_button',
  bottomDashboardByText: 'android=new UiSelector().textContains("Dashboard")',
  bottomSettingsByText: 'android=new UiSelector().textContains("Settings")',
  navTasksByText: 'android=new UiSelector().textContains("Tasks")',
  navNotificationsByText: 'android=new UiSelector().textContains("Notifications")'
};
