<?php
require_once __DIR__ . '/rmi_icons.php';
/**
 * _shared/nav_config.php
 * ──────────────────────────────────────────────────────────────────────────
 * KONFIGURASI SIDEBAR — Server-side filtered per dept/role.
 *
 * SETIAP item HARUS punya 'key' unik agar bisa diatur via Nav Manager.
 * Jika punya 'url' → URL tersebut yang dipakai (bukan dari $u di rmi_layout).
 * Jika hanya 'key' tanpa 'url' → URL diambil dari $u di rmi_layout.php.
 * Key lama Nav Manager tanpa URL (mis. absensi_admin, hrl_reg_alkes, hrl_payroll)
 * tetap didukung lewat entri $u + $_permByKey di rmi_layout.php — tidak wajib migrasi.
 *
 * Format:
 *   ['section' => 'LABEL']                                — pemisah grup
 *   ['key' => 'unik_key', 'icon'=>'', 'label'=>'', 'roles'=>'']
 *   ['key' => '...', 'url' => '{base}/path.php', ...]    — URL eksplisit
 *   ['hrl_tower_type' => 'CUTI', ...]                    — opsional: izin sidebar = hrlp_req_type_nav_permissions()
 *
 * 'roles' = comma-separated dept list, atau 'ALL'.
 * SYS (admin) selalu lihat semua (bypass di rmi_layout.php).
 */
return [

    // ══════════════════════════════════════════════════════════════════════
    // DEFAULT — non-BRANCH (CRM, SCM, WQS, PQP, FIN, ACT, HRL, ITC, MPR)
    // ══════════════════════════════════════════════════════════════════════
    'default' => [

        // ── MAIN ─────────────────────────────────────────────────────────
        ['section' => 'MAIN'],
        ['key' => 'dashboard',
         'url' => '{base}/dashboards/index.php',
         'icon' => rmi_icon('chart'), 'label' => 'Dashboard Center',
         'roles' => 'ALL'],
        ['key' => 'branch_dashboard',
         'url' => '{base}/dashboards/branch/branch_dashboard.php',
         'icon' => rmi_icon('office'), 'label' => 'Branch Dashboard',
         'roles' => 'BRANCH'],
        ['key' => 'branch_panduan',
         'url' => '{base}/dashboards/branch/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan BRANCH',
         'roles' => 'BRANCH',
         'perm' => ['DASHBOARD.BRANCH_VIEW']],
        // ── ABSENSI (paket menu — selaras page_registry & RBAC) ───────────
        ['section' => 'ABSENSI'],
        ['key' => 'absensi',
         'url' => '{base}/absensi/index.php',
         'icon' => rmi_icon('home'), 'label' => 'Absensi — Beranda',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.VIEW', 'ABSENSI.CHECKIN']],
        ['key' => 'absensi_checkin',
         'url' => '{base}/absensi/checkin.php',
         'icon' => rmi_icon('target'), 'label' => 'Check-in',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.CHECKIN']],
        ['key' => 'absensi_checkout',
         'url' => '{base}/absensi/checkout.php',
         'icon' => rmi_icon('home'), 'label' => 'Check-out',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.CHECKIN']],
        ['key' => 'absensi_history',
         'url' => '{base}/absensi/history.php',
         'icon' => rmi_icon('doc'), 'label' => 'Riwayat',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.VIEW']],
        ['key' => 'absensi_request',
         'url' => '{base}/absensi/request.php',
         'icon' => rmi_icon('memo'), 'label' => 'Pengajuan',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.REQUEST', 'ABSENSI.VIEW']],
        ['key' => 'absensi_izin',
         'url' => '{base}/absensi/izin.php',
         'icon' => rmi_icon('sun'), 'label' => 'Izin / Dinas',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.REQUEST', 'ABSENSI.VIEW']],
        ['key' => 'absensi_approval',
         'url' => '{base}/absensi/approval.php',
         'icon' => rmi_icon('check'), 'label' => 'Approval',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.APPROVE']],
        ['key' => 'absensi_panduan',
         'url' => '{base}/absensi/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan Absensi',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.VIEW']],
        // ── ABSENSI ADMIN (selaras blok ABSENSI ADMIN di page_registry) ────
        ['section' => 'ABSENSI ADMIN'],
        ['key' => 'absensi_admin_panel',
         'url' => '{base}/absensi/admin.php',
         'icon' => rmi_icon('gear'), 'label' => 'Admin — Panel',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_USERS']],
        ['key' => 'absensi_admin_rekap',
         'url' => '{base}/absensi/admin/rekap.php',
         'icon' => rmi_icon('clipboard'), 'label' => 'Admin — Rekap',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.RECAP']],
        ['key' => 'absensi_admin_approval',
         'url' => '{base}/absensi/admin/approval.php',
         'icon' => rmi_icon('check'), 'label' => 'Admin — Approval',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.APPROVE', 'ABSENSI.VIEW']],
        ['key' => 'absensi_admin_offices',
         'url' => '{base}/absensi/admin/offices.php',
         'icon' => rmi_icon('target'), 'label' => 'Admin — Office / GeoFence',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.OFFICE_SETTINGS']],
        ['key' => 'absensi_admin_pins',
         'url' => '{base}/absensi/admin/pins.php',
         'icon' => rmi_icon('memo'), 'label' => 'Admin — PIN',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_PINS']],
        ['key' => 'absensi_admin_user_map',
         'url' => '{base}/absensi/admin/users.php',
         'icon' => rmi_icon('users'), 'label' => 'Admin — Users Mapping',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_USERS', 'ABSENSI.ADMIN_EDIT']],
        ['key' => 'absensi_admin_shifts',
         'url' => '{base}/absensi/admin/shifts.php',
         'icon' => rmi_icon('calendar'), 'label' => 'Admin — Shift',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_EDIT']],
        ['key' => 'absensi_admin_settings',
         'url' => '{base}/absensi/admin/settings.php',
         'icon' => rmi_icon('gear'), 'label' => 'Admin — Settings',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_EDIT']],
        ['key' => 'absensi_admin_broadcast',
         'url' => '{base}/absensi/admin/broadcast.php',
         'icon' => rmi_icon('zap'), 'label' => 'Admin — Broadcast',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_EDIT']],
        ['key' => 'absensi_admin_payroll_gate',
         'url' => '{base}/absensi/admin/payroll_gate.php',
         'icon' => rmi_icon('money'), 'label' => 'Admin — Payroll Gate',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_EDIT']],
        ['key' => 'absensi_kiosk',
         'url' => '{base}/absensi/kiosk.php',
         'icon' => rmi_icon('gear'), 'label' => 'Kiosk Absensi',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.CHECKIN', 'ABSENSI.VIEW']],
        ['key' => 'absensi_kiosk_poster',
         'url' => '{base}/absensi/admin/kiosk_poster.php',
         'icon' => rmi_icon('doc'), 'label' => 'Kiosk — Poster',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_EDIT']],
        // ── KPI (selaras blok KPI di page_registry) ─────────────────────────
        ['section' => 'KPI'],
        ['key' => 'kpi',
         'url' => '{base}/kpi/kpi_center.php',
         'icon' => rmi_icon('trend'), 'label' => 'KPI Center',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.VIEW']],
        ['key' => 'kpi_dashboard_daily',
         'url' => '{base}/kpi/kpi_dashboard_daily.php',
         'icon' => rmi_icon('calendar'), 'label' => 'KPI — Dashboard Harian',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.VIEW', 'DASHBOARD.KPI_VIEW']],
        ['key' => 'kpi_dashboard_monthly',
         'url' => '{base}/kpi/kpi_dashboard_monthly.php',
         'icon' => rmi_icon('calendar'), 'label' => 'KPI — Dashboard Bulanan',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.VIEW', 'DASHBOARD.KPI_VIEW']],
        ['key' => 'kpi_do_audit',
         'url' => '{base}/kpi/kpi_do_audit.php',
         'icon' => rmi_icon('search'), 'label' => 'KPI — DO Audit',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.DO_AUDIT']],
        ['key' => 'kpi_do_sla',
         'url' => '{base}/kpi/kpi_do_sla.php',
         'icon' => rmi_icon('calendar'), 'label' => 'KPI — SLA DO',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.DO_VIEW']],
        ['key' => 'kpi_purchases',
         'url' => '{base}/kpi/kpi_purchases.php',
         'icon' => rmi_icon('cart'), 'label' => 'KPI — Purchases',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.PURCHASES_VIEW']],
        ['key' => 'kpi_stock',
         'url' => '{base}/kpi/kpi_stock.php',
         'icon' => rmi_icon('box'), 'label' => 'KPI — Stock',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.STOCK_VIEW']],
        ['key' => 'kpi_employee',
         'url' => '{base}/kpi/kpi_employee.php',
         'icon' => rmi_icon('user'), 'label' => 'KPI — Employee',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.EMPLOYEE_VIEW']],
        ['key' => 'kpi_office',
         'url' => '{base}/kpi/kpi_office.php',
         'icon' => rmi_icon('office'), 'label' => 'KPI — Office / Cabang',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.OFFICE_VIEW']],
        ['key' => 'kpi_snapshot',
         'url' => '{base}/kpi/kpi_snapshot.php',
         'icon' => rmi_icon('doc'), 'label' => 'KPI — Snapshot',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.VIEW']],
        ['key' => 'kpi_audit',
         'url' => '{base}/kpi/kpi_audit.php',
         'icon' => rmi_icon('doc'), 'label' => 'KPI — Dashboard Audit',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.DO_AUDIT']],
        ['key' => 'kpi_panduan',
         'url' => '{base}/kpi/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'KPI — Panduan',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,SYS',
         'perm' => ['KPI.VIEW']],
        ['key' => 'chat',
         'icon' => rmi_icon('users'), 'label' => 'Internal Chat',
         'roles' => 'ALL'],
        ['key' => 'help_center',
         'url' => '{base}/docs/help_center.php',
         'icon' => rmi_icon('question'), 'label' => 'Help Center',
         'roles' => 'ALL'],
        ['key' => 'exec_summary',
         'icon' => rmi_icon('target'), 'label' => 'Executive Summary',
         'roles' => 'SYS'],

        // ── CRM ───────────────────────────────────────────────────────────
        ['section' => 'CRM'],
        ['key' => 'sales',
         'url' => '{base}/sales/sales_dashboard.php',
         'icon' => rmi_icon('receipt'), 'label' => 'Sales Dashboard',
         'roles' => 'CRM,SYS'],
        ['key' => 'crm_control_tower',
         'url' => '{base}/sales/sales_control_tower.php',
         'icon' => rmi_icon('tower'), 'label' => 'Control Tower',
         'roles' => 'CRM,BRANCH,SYS'],
        ['key' => 'crm_control_tower_panduan',
         'url' => '{base}/sales/panduan_control_tower.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan Sales Tower',
         'roles' => 'CRM,BRANCH,SYS'],
        ['key' => 'crm_sales_panduan',
         'url' => '{base}/sales/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan Sales & DO',
         'roles' => 'CRM,BRANCH,HRL,FIN,ACT,SCM,PQP,MPR,SYS',
         'perm' => ['PANDUAN.SALES_VIEW', 'SALES.VIEW', 'DASHBOARD.SALES_VIEW']],
        ['key' => 'crm_do',
         'url' => '{base}/sales/sales_do.php',
         'icon' => rmi_icon('clipboard'), 'label' => 'Delivery Order',
         'roles' => 'CRM,BRANCH,SYS'],
        ['key' => 'wqs_do_tasks',
         'icon' => rmi_icon('zap'), 'label' => 'Task DO (WQS)',
         'roles' => 'CRM,BRANCH,SYS'],
        ['key' => 'wqs_picking',
         'icon' => rmi_icon('refresh'), 'label' => 'Picking DO',
         'roles' => 'CRM,WQS,BRANCH,SYS'],

        // ── SCM ───────────────────────────────────────────────────────────
        ['section' => 'SCM'],
        ['key' => 'scm_dashboard',
         'url' => '{base}/dashboards/scm/scm_dashboard.php',
         'icon' => rmi_icon('outbox'), 'label' => 'SCM Dashboard',
         'roles' => 'SCM,SYS'],
        ['key' => 'scm_panduan',
         'url' => '{base}/dashboards/scm/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan SCM',
         'roles' => 'SCM,SYS'],
        ['key' => 'scm_import_ct',
         'url' => '{base}/purchases/purchases_import_control_tower.php',
         'icon' => rmi_icon('tower'), 'label' => 'Import Control Tower',
         'roles' => 'SCM,PQP,SYS'],
        ['key' => 'purchases_forwarding',
         'icon' => rmi_icon('box'), 'label' => 'Forwarding Tasks',
         'roles' => 'SCM,PQP,SYS'],
        ['key' => 'scm_do_tasks',
         'icon' => rmi_icon('outbox'), 'label' => 'SCM Task DO',
         'roles' => 'SCM,WQS,BRANCH,SYS'],
        ['key' => 'scm_po',
         'url' => '{base}/purchases/purchases_po.php',
         'icon' => rmi_icon('doc'), 'label' => 'Purchase Order (PO)',
         'roles' => 'SCM,PQP,BRANCH,SYS'],
        ['key' => 'scm_gr',
         'url' => '{base}/purchases/purchases_gr.php',
         'icon' => rmi_icon('check'), 'label' => 'Good Receipt (GR)',
         'roles' => 'SCM,PQP,WQS,BRANCH,SYS'],
        ['key' => 'scm_pr',
         'url' => '{base}/stock/wqs_pr.php',
         'icon' => rmi_icon('memo'), 'label' => 'Purchase Request',
         'roles' => 'SCM,WQS,SYS'],

        // ── WQS ───────────────────────────────────────────────────────────
        ['section' => 'WQS'],
        ['key' => 'stock',
         'icon' => rmi_icon('box'), 'label' => 'WQS Dashboard',
         'roles' => 'WQS,SCM,SYS'],
        ['key' => 'wqs_incoming',
         'url' => '{base}/stock/wqs_incoming.php',
         'icon' => rmi_icon('inbox'), 'label' => 'Incoming',
         'roles' => 'WQS,SCM,PQP,BRANCH,SYS'],
        ['key' => 'wqs_stock_view',
         'url' => '{base}/stock/wqs_stock.php',
         'icon' => rmi_icon('chart'), 'label' => 'Lihat Stok',
         'roles' => 'WQS,SCM,BRANCH,SYS'],
        ['key' => 'wqs_allocation',
         'url' => '{base}/stock/wqs_allocation.php',
         'icon' => rmi_icon('box'), 'label' => 'Allocation',
         'roles' => 'WQS,SYS'],
        ['key' => 'stock_opname',
         'icon' => rmi_icon('memo'), 'label' => 'Stock Opname',
         'roles' => 'WQS,SYS'],
        ['key' => 'wqs_pr',
         'url' => '{base}/stock/wqs_pr.php',
         'icon' => rmi_icon('memo'), 'label' => 'Purchase Request',
         'roles' => 'WQS,BRANCH,SYS'],

        // ── PQP ───────────────────────────────────────────────────────────
        ['section' => 'PQP'],
        ['key' => 'purchases',
         'url' => '{base}/purchases/purchases_dashboard.php',
         'icon' => rmi_icon('cart'), 'label' => 'PQP Dashboard',
         'roles' => 'PQP,SCM,SYS'],
        ['key' => 'purchases_rfq',
         'icon' => rmi_icon('clipboard'), 'label' => 'RFQ',
         'roles' => 'PQP,SCM,SYS'],
        ['key' => 'purchases_po',
         'icon' => rmi_icon('doc'), 'label' => 'Purchase Order (PO)',
         'roles' => 'PQP,SYS'],
        ['key' => 'pqp_gr',
         'url' => '{base}/purchases/purchases_gr.php',
         'icon' => rmi_icon('check'), 'label' => 'Good Receipt (GR)',
         'roles' => 'PQP,WQS,SYS'],
        ['key' => 'pqp_import_ct',
         'url' => '{base}/purchases/purchases_import_control_tower.php',
         'icon' => rmi_icon('tower'), 'label' => 'Import Control Tower',
         'roles' => 'PQP,SCM,SYS'],
        ['key' => 'pqp_import_ct_panduan',
         'url' => '{base}/purchases/panduan_import_tower.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan Import Tower',
         'roles' => 'PQP,SCM,FIN,SYS'],
        ['key' => 'pqp_purchases_panduan',
         'url' => '{base}/purchases/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan Purchases',
         'roles' => 'PQP,SCM,FIN,ACT,WQS,HRL,BRANCH,SYS',
         'perm' => ['PANDUAN.PURCHASES_VIEW', 'PURCHASES.VIEW', 'DASHBOARD.PROCUREMENT_VIEW']],
        // CEISA / Reports harus sebelum marker REG ALKES: jika semua item Reg Alkes
        // disembunyikan oleh RBAC, header "REG ALKES" tidak boleh menempel ke item PQP ini.
        ['key' => 'purchases_ceisa_pib',
         'url' => '{base}/purchases/purchases_ceisa_pib.php',
         'icon' => rmi_icon('office'), 'label' => 'CEISA / PIB',
         'roles' => 'ACT,PQP,SCM,FIN,SYS',
         // Tanpa PURCHASES.VIEW: hindari cabang/staff dengan view PO umum melihat menu bea cukai.
         'perm' => ['PURCHASES.CEISA_PIB', 'PURCHASES.CEISA_VIEW', 'PURCHASES.CEISA_EDIT']],
        ['key' => 'purchases_reports',
         'url' => '{base}/purchases/purchases_reports.php',
         'icon' => rmi_icon('chart'), 'label' => 'Purchases Reports',
         'roles' => 'PQP,SCM,FIN,ACT,SYS',
         'perm' => ['PURCHASES.REPORTS_VIEW', 'PURCHASES.AP_INVOICE_CRUD', 'PURCHASES.AP_PAYMENT_CRUD']],
        // ── REG ALKES (selaras blok HRL REG ALKES di page_registry) ───────
        ['section' => 'REG ALKES'],
        ['key' => 'hrl_reg_alkes_dashboard',
         'url' => '{base}/hrl_reg_alkes/index.php',
         'icon' => rmi_icon('search'), 'label' => 'Reg Alkes — Dashboard',
         'roles' => 'PQP,HRL,SYS',
         'perm' => ['HRL.REG_ALKES_VIEW']],
        ['key' => 'hrl_reg_alkes_data',
         'url' => '{base}/hrl_reg_alkes/reg_alkes.php',
         'icon' => rmi_icon('clipboard'), 'label' => 'Reg Alkes — Data NIE',
         'roles' => 'PQP,HRL,SYS',
         'perm' => ['HRL.REG_ALKES_VIEW']],
        ['key' => 'hrl_reg_alkes_case',
         'url' => '{base}/hrl_reg_alkes/reg_alkes_case.php',
         'icon' => rmi_icon('doc'), 'label' => 'Reg Alkes — Case',
         'roles' => 'PQP,HRL,SYS',
         'perm' => ['HRL.REG_ALKES_VIEW']],
        ['key' => 'hrl_reg_alkes_control_tower',
         'url' => '{base}/hrl_reg_alkes/reg_alkes_control_tower.php',
         'icon' => rmi_icon('tower'), 'label' => 'Reg Alkes — Control Tower',
         'roles' => 'PQP,HRL,SYS',
         'perm' => ['HRL.REG_ALKES_VIEW']],
        ['key' => 'hrl_reg_alkes_expiry',
         'url' => '{base}/hrl_reg_alkes/reg_alkes_expiry_check.php',
         'icon' => rmi_icon('calendar'), 'label' => 'Reg Alkes — Expiry',
         'roles' => 'PQP,HRL,SYS',
         'perm' => ['HRL.REG_ALKES_VIEW']],
        ['key' => 'hrl_reg_alkes_export_compliance',
         'url' => '{base}/hrl_reg_alkes/reg_alkes_export_compliance.php',
         'icon' => rmi_icon('outbox'), 'label' => 'Reg Alkes — Export Compliance',
         'roles' => 'PQP,HRL,SYS',
         'perm' => ['HRL.COMPLIANCE_EXPORT']],
        ['key' => 'hrl_reg_alkes_sku_nie',
         'url' => '{base}/hrl_reg_alkes/reg_alkes_sku_by_nie.php',
         'icon' => rmi_icon('search'), 'label' => 'Reg Alkes — SKU by NIE',
         'roles' => 'PQP,HRL,SYS',
         'perm' => ['HRL.REG_ALKES_VIEW']],
        ['key' => 'hrl_reg_alkes_panduan',
         'url' => '{base}/hrl_reg_alkes/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Reg Alkes — Panduan',
         'roles' => 'PQP,HRL,SYS',
         'perm' => ['HRL.REG_ALKES_VIEW']],

        // ── FIN ───────────────────────────────────────────────────────────
        ['section' => 'FIN'],
        ['key' => 'fin_dashboard',
         'url' => '{base}/dashboards/finance/ar_ap_cash_dashboard.php',
         'icon' => rmi_icon('money'), 'label' => 'Finance Dashboard',
         'roles' => 'FIN,SYS',
         'perm' => ['DASHBOARD.FINANCE_VIEW']],
        ['key' => 'fin_finance_ap_rekap',
         'url' => '{base}/dashboards/finance/ap_rekap.php',
         'icon' => rmi_icon('chart'), 'label' => 'Finance — AP Rekap',
         'roles' => 'FIN,SYS',
         'perm' => ['DASHBOARD.FINANCE_VIEW']],
        ['key' => 'fin_finance_gl_rekap',
         'url' => '{base}/dashboards/finance/gl_rekap.php',
         'icon' => rmi_icon('doc'), 'label' => 'Finance — GL Rekap',
         'roles' => 'FIN,SYS',
         'perm' => ['DASHBOARD.FINANCE_VIEW']],
        ['key' => 'fin_finance_dashboard_detail',
         'url' => '{base}/dashboards/finance/dashboard_detail.php',
         'icon' => rmi_icon('search'), 'label' => 'Finance — Dashboard Detail',
         'roles' => 'FIN,SYS',
         'perm' => ['DASHBOARD.FINANCE_DETAIL']],
        ['key' => 'fin_finance_sales_do_rekap',
         'url' => '{base}/dashboards/finance/sales_do_rekap.php',
         'icon' => rmi_icon('outbox'), 'label' => 'Finance — Sales DO Rekap',
         'roles' => 'FIN,SYS',
         'perm' => ['DASHBOARD.FINANCE_VIEW']],
        ['key' => 'fin_finance_target_rekap',
         'url' => '{base}/dashboards/finance/target_rekap.php',
         'icon' => rmi_icon('target'), 'label' => 'Finance — Target Rekap',
         'roles' => 'FIN,SYS',
         'perm' => ['DASHBOARD.FINANCE_VIEW']],
        ['key' => 'fin_finance_panduan',
         'url' => '{base}/dashboards/finance/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Finance — Panduan',
         'roles' => 'FIN,SYS',
         'perm' => ['DASHBOARD.FINANCE_VIEW']],
        ['key' => 'fin_do_tasks',
         'url' => '{base}/sales/fin_do_tasks.php',
         'icon' => rmi_icon('zap'), 'label' => 'FIN Task DO',
         'roles' => 'FIN,SYS'],
        ['key' => 'purchases_invoice_ap',
         'icon' => rmi_icon('receipt'), 'label' => 'AP Invoice',
         'roles' => 'FIN,ACT,SYS'],
        ['key' => 'purchases_ap',
         'icon' => rmi_icon('money'), 'label' => 'AP Payment',
         'roles' => 'FIN,ACT,SYS'],
        ['key' => 'tax_invoice',
         'url' => '{base}/sales/tax_invoices.php',
         'icon' => rmi_icon('receipt'), 'label' => 'Tax Invoice',
         'roles' => 'FIN,ACT,SYS'],
        ['key' => 'bank_recon',
         'url' => '{base}/purchases/bank_recon.php',
         'icon' => rmi_icon('money'), 'label' => 'Bank Rekonsiliasi',
         'roles' => 'FIN,ACT,SYS'],
        ['key' => 'company_bank',
         'icon' => rmi_icon('money'), 'label' => 'Rekening Perusahaan',
         'roles' => 'FIN,SYS'],
        // ── PAYROLL (selaras blok PAYROLL di page_registry) ───────────────
        ['section' => 'PAYROLL'],
        ['key' => 'payroll',
         'url' => '{base}/payroll/index.php',
         'icon' => rmi_icon('money'), 'label' => 'Payroll — Beranda',
         'roles' => 'FIN,HRL,SYS',
         'perm' => ['PAYROLL.VIEW']],
        ['key' => 'payroll_run',
         'url' => '{base}/payroll/payroll_run.php',
         'icon' => rmi_icon('zap'), 'label' => 'Payroll Run',
         'roles' => 'FIN,HRL,SYS',
         'perm' => ['PAYROLL.VIEW']],
        ['key' => 'payroll_salary_matrix',
         'url' => '{base}/payroll/salary_matrix.php',
         'icon' => rmi_icon('gear'), 'label' => 'Matrix Kompensasi',
         'roles' => 'FIN,HRL,SYS',
         'perm' => ['PAYROLL.MATRIX_VIEW']],
        ['key' => 'payroll_loans',
         'url' => '{base}/payroll/loans.php',
         'icon' => rmi_icon('money'), 'label' => 'Kasbon / Pinjaman',
         'roles' => 'FIN,HRL,SYS',
         'perm' => ['PAYROLL.LOANS_VIEW']],
        ['key' => 'payroll_payslip',
         'url' => '{base}/payroll/payslip.php',
         'icon' => rmi_icon('receipt'), 'label' => 'Payslip',
         'roles' => 'FIN,HRL,SYS',
         'perm' => ['PAYROLL.PAYSLIP_VIEW']],
        ['key' => 'payroll_settings',
         'url' => '{base}/payroll/payroll_settings.php',
         'icon' => rmi_icon('gear'), 'label' => 'Payroll Settings',
         'roles' => 'FIN,HRL,SYS',
         'perm' => ['PAYROLL.SETTINGS']],
        ['key' => 'payroll_audit',
         'url' => '{base}/payroll/audit.php',
         'icon' => rmi_icon('doc'), 'label' => 'Payroll Audit',
         'roles' => 'FIN,HRL,SYS',
         'perm' => ['PAYROLL.AUDIT']],
        ['key' => 'payroll_panduan',
         'url' => '{base}/payroll/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Payroll — Panduan',
         'roles' => 'FIN,HRL,SYS',
         'perm' => ['PAYROLL.VIEW']],

        // ── ACT ───────────────────────────────────────────────────────────
        ['section' => 'ACT'],
        ['key' => 'act_dashboard',
         'url' => '{base}/dashboards/act/act_dashboard.php',
         'icon' => rmi_icon('memo'), 'label' => 'ACT Dashboard',
         'roles' => 'ACT,SYS'],
        ['key' => 'act_do_tasks',
         'url' => '{base}/sales/act_do_tasks.php',
         'icon' => rmi_icon('zap'), 'label' => 'ACT Task DO',
         'roles' => 'ACT,SYS'],
        ['key' => 'fin_ap_invoice',
         'url' => '{base}/purchases/purchases_invoice_ap.php',
         'icon' => rmi_icon('receipt'), 'label' => 'AP Invoice',
         'roles' => 'ACT,FIN,SYS'],
        ['key' => 'fin_ap_payment',
         'url' => '{base}/purchases/purchases_payment_ap.php',
         'icon' => rmi_icon('money'), 'label' => 'AP Payment',
         'roles' => 'ACT,FIN,SYS'],
        ['key' => 'act_tax',
         'url' => '{base}/sales/tax_invoices.php',
         'icon' => rmi_icon('receipt'), 'label' => 'Tax Invoice',
         'roles' => 'ACT,FIN,SYS'],
        ['key' => 'fin_bank_recon',
         'url' => '{base}/purchases/bank_recon.php',
         'icon' => rmi_icon('money'), 'label' => 'Bank Rekonsiliasi',
         'roles' => 'ACT,FIN,SYS'],
        ['key' => 'master_tax',
         'url' => '{base}/master/master_tax.php',
         'icon' => rmi_icon('chart'), 'label' => 'Master Tax',
         'roles' => 'ACT,SYS'],

        // ── FIXED ASSET (alur terpisah — selaras Nav Manager / registry) ─
        ['section' => 'FIXED ASSET'],
        ['key' => 'fixed_asset',
         'url' => '{base}/Fixed_Asset/index.php',
         'icon' => rmi_icon('office'), 'label' => 'FA — Dashboard',
         'roles' => 'ACT,FIN,SYS',
         'perm' => ['FIXED_ASSET.VIEW']],
        ['key' => 'fixed_asset_assets',
         'url' => '{base}/Fixed_Asset/assets.php',
         'icon' => rmi_icon('box'), 'label' => 'FA — Daftar Aset',
         'roles' => 'ACT,FIN,SYS',
         'perm' => ['FIXED_ASSET.ASSET_CRUD', 'FIXED_ASSET.ASSET_VIEW']],
        ['key' => 'fixed_asset_ops',
         'url' => '{base}/Fixed_Asset/ops.php',
         'icon' => rmi_icon('gear'), 'label' => 'FA — Operasional',
         'roles' => 'ACT,FIN,SYS',
         'perm' => ['FIXED_ASSET.OPERATIONS', 'FIXED_ASSET.OPS_VIEW', 'FIXED_ASSET.OPS_EDIT']],
        ['key' => 'fixed_asset_depreciation',
         'url' => '{base}/Fixed_Asset/depreciation.php',
         'icon' => rmi_icon('trend'), 'label' => 'FA — Depresiasi',
         'roles' => 'ACT,FIN,SYS',
         'perm' => ['FIXED_ASSET.DEPRECIATION_RUN', 'FIXED_ASSET.VIEW']],
        ['key' => 'fixed_asset_tax_annual',
         'url' => '{base}/Fixed_Asset/tax_annual.php',
         'icon' => rmi_icon('chart'), 'label' => 'FA — Pajak Tahunan',
         'roles' => 'ACT,FIN,SYS',
         'perm' => ['FIXED_ASSET.TAX_ANNUAL', 'FIXED_ASSET.TAX_ANNUAL_VIEW', 'FIXED_ASSET.TAX_ANNUAL_EDIT']],
        ['key' => 'fixed_asset_audit',
         'url' => '{base}/Fixed_Asset/audit.php',
         'icon' => rmi_icon('search'), 'label' => 'FA — Audit',
         'roles' => 'ACT,FIN,SYS',
         'perm' => ['FIXED_ASSET.AUDIT_VIEW', 'FIXED_ASSET.AUDIT']],
        ['key' => 'fixed_asset_panduan',
         'url' => '{base}/Fixed_Asset/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'FA — Panduan',
         'roles' => 'ACT,FIN,SYS',
         'perm' => ['FIXED_ASSET.VIEW']],

        // ── HRL ───────────────────────────────────────────────────────────
        ['section' => 'HRL'],
        ['key' => 'hrl_dashboard',
         'url' => '{base}/dashboards/hrl/hrl_dashboard.php',
         'icon' => rmi_icon('users'), 'label' => 'HRL Dashboard',
         'roles' => 'HRL,SYS'],
        ['key' => 'hrl',
         'icon' => rmi_icon('books'), 'label' => 'HRL Docs',
         'roles' => 'HRL,SYS'],
        ['key' => 'hrl_rekap',
         'url' => '{base}/absensi/admin/rekap.php',
         'icon' => rmi_icon('clipboard'), 'label' => 'Rekap Absensi',
         'roles' => 'HRL,SYS'],
        ['key' => 'master_employees',
         'url' => '{base}/master/master_employees.php',
         'icon' => rmi_icon('user'), 'label' => 'Master Karyawan',
         'roles' => 'HRL,SYS'],

        // ── HRL PROCESS — lintas dept (tower.php + deep link per tipe) ───
        ['section' => 'HRL PROCESS'],
        ['key' => 'hrl_process',
         'url' => '{base}/hrl_process/tower.php',
         'icon' => rmi_icon('refresh'), 'label' => 'HRL Process Tower',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,BRANCH,SYS'],
        ['key' => 'hrl_tower_cuti',
         'url' => '{base}/hrl_process/tower.php?req_type=CUTI',
         'icon' => rmi_icon('sun'), 'label' => 'Pengajuan — Cuti',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,BRANCH,SYS',
         'hrl_tower_type' => 'CUTI'],
        ['key' => 'hrl_tower_izin',
         'url' => '{base}/hrl_process/tower.php?req_type=IZIN',
         'icon' => rmi_icon('clipboard'), 'label' => 'Pengajuan — Izin',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,BRANCH,SYS',
         'hrl_tower_type' => 'IZIN'],
        ['key' => 'hrl_tower_lembur',
         'url' => '{base}/hrl_process/tower.php?req_type=LEMBUR',
         'icon' => rmi_icon('calendar'), 'label' => 'Pengajuan — Lembur',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,BRANCH,SYS',
         'hrl_tower_type' => 'LEMBUR'],
        ['key' => 'hrl_tower_perjadin',
         'url' => '{base}/hrl_process/tower.php?req_type=PERJADIN',
         'icon' => rmi_icon('outbox'), 'label' => 'Pengajuan — Perjadin',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,BRANCH,SYS',
         'hrl_tower_type' => 'PERJADIN'],
        ['key' => 'hrl_tower_permintaan_karyawan',
         'url' => '{base}/hrl_process/tower.php?req_type=PERMINTAAN_KARYAWAN',
         'icon' => rmi_icon('box'), 'label' => 'Pengajuan — Permintaan Karyawan',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,BRANCH,SYS',
         'hrl_tower_type' => 'PERMINTAAN_KARYAWAN'],
        ['key' => 'hrl_tower_kenaikan_gaji',
         'url' => '{base}/hrl_process/tower.php?req_type=KENAIKAN_GAJI',
         'icon' => rmi_icon('money'), 'label' => 'Pengajuan — Kenaikan Gaji',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,BRANCH,SYS',
         'hrl_tower_type' => 'KENAIKAN_GAJI'],
        ['key' => 'hrl_tower_rekrutmen',
         'url' => '{base}/hrl_process/tower.php?req_type=REKRUTMEN',
         'icon' => rmi_icon('users'), 'label' => 'Pengajuan — Rekrutmen',
         'roles' => 'CRM,SCM,WQS,PQP,FIN,ACT,HRL,ITC,MPR,BRANCH,SYS',
         'hrl_tower_type' => 'REKRUTMEN'],

        // ── ITC ───────────────────────────────────────────────────────────
        ['section' => 'ITC'],
        ['key' => 'itc_dashboard',
         'url' => '{base}/dashboards/itc/itc_dashboard.php',
         'icon' => rmi_icon('gear'), 'label' => 'ITC Dashboard',
         'roles' => 'ITC,SYS'],
        ['key' => 'itc_users',
         'url' => '{base}/master/itc_reset_password.php',
         'icon' => rmi_icon('users'), 'label' => 'Manajemen User',
         'roles' => 'ITC,SYS'],
        ['key' => 'rbac',
         'icon' => rmi_icon('gear'), 'label' => 'RBAC',
         'roles' => 'ITC,SYS'],
        ['key' => 'nav_manager',
         'icon' => rmi_icon('box'), 'label' => 'Nav Manager',
         'roles' => 'ITC,SYS'],
        ['key' => 'tools',
         'icon' => rmi_icon('gear'), 'label' => 'Tools',
         'roles' => 'ITC,SYS'],
        ['key' => 'system_config',
         'url' => '{base}/master/master_system_config.php',
         'icon' => rmi_icon('gear'), 'label' => 'System Config',
         'roles' => 'ITC,SYS'],

        // ── MPR (Marketing & Project; FIN ikut policy /mpr/*) ────────────
        ['section' => 'MPR'],
        ['key' => 'mpr_main',
         'url' => '{base}/mpr/mpr_dashboard.php',
         'icon' => rmi_icon('chart'), 'label' => 'MPR Dashboard',
         'roles' => 'MPR,FIN,SYS',
         'perm' => ['MPR.VIEW']],
        ['key' => 'mpr_plans',
         'url' => '{base}/mpr/mpr_plans.php',
         'icon' => rmi_icon('search'), 'label' => 'MPR Plans',
         'roles' => 'MPR,FIN,SYS',
         'perm' => ['MPR.PLAN_VIEW', 'MPR.PLAN_CREATE', 'MPR.VIEW']],
        ['key' => 'mpr_pipeline',
         'url' => '{base}/mpr/mpr_pipeline.php',
         'icon' => rmi_icon('search'), 'label' => 'Sales Pipeline',
         'roles' => 'MPR,FIN,SYS',
         'perm' => ['MPR.VIEW']],
        ['key' => 'mpr_visits',
         'url' => '{base}/mpr/mpr_visits.php',
         'icon' => rmi_icon('user'), 'label' => 'MPR Visits',
         'roles' => 'MPR,FIN,SYS',
         'perm' => ['MPR.VIEW', 'MPR.PLAN_CREATE']],
        ['key' => 'mpr_budget_fin',
         'url' => '{base}/mpr/mpr_budget_fin.php',
         'icon' => rmi_icon('money'), 'label' => 'MPR Budget (FIN)',
         'roles' => 'FIN,MPR,SYS',
         'perm' => ['MPR.VIEW']],
        ['key' => 'mpr_ops_daily_fin',
         'url' => '{base}/mpr/mpr_ops_daily_fin.php',
         'icon' => rmi_icon('calendar'), 'label' => 'MPR Ops Harian',
         'roles' => 'FIN,MPR,SYS',
         'perm' => ['MPR.VIEW']],
        ['key' => 'mpr_panduan',
         'url' => '{base}/mpr/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan MPR',
         'roles' => 'MPR,FIN,SYS',
         'perm' => ['MPR.VIEW']],

        // ── SYSTEM (ADMIN only) ───────────────────────────────────────────
        ['section' => 'SYSTEM'],
        ['key' => 'master',
         'icon' => rmi_icon('home'), 'label' => 'Master Data',
         'roles' => 'ITC,SYS'],
        // ── Master Data Center — pintasan selaras mod_card (tanpa duplikasi label berlebihan)
        ['section' => 'MASTER HUB'],
        [
  'key' => 'mh_master_manufactures',
  'url' => '{base}/master/master_manufactures.php',
  'icon' => rmi_icon('office'),
  'label' => 'Master Manufactures',
  'roles' => 'PQP,SCM,ITC,SYS',
  'perm' => ['MASTER.MANUFACTURE_VIEW', 'MASTER.VIEW']
],
[
  'key' => 'mh_master_manufacturer_portal_users',
  'url' => '{base}/master/master_manufacturer_portal_users.php',
  'icon' => rmi_icon('user'),
  'label' => 'Manufacturer Portal Users',
  'roles' => 'PQP,SCM,ITC,SYS',
  'perm' => ['MASTER.MANUFACTURE_PORTAL', 'MASTER.VIEW']
],
        ['key' => 'docs_modules_hub',
         'url' => '{base}/docs/modules_hub.php',
         'icon' => rmi_icon('books'), 'label' => 'Modules Hub',
         'roles' => 'ALL',
         'perm' => ['DOCS.VIEW']],
        ['key' => 'mh_master_products',
         'url' => '{base}/master/master_products.php',
         'icon' => rmi_icon('box'), 'label' => 'Master Products',
         'roles' => 'CRM,SCM,PQP,WQS,ITC,SYS',
         'perm' => ['MASTER.PRODUCT_VIEW', 'MASTER.VIEW']],
        ['key' => 'mh_master_office',
         'url' => '{base}/master/master_office.php',
         'icon' => rmi_icon('office'), 'label' => 'Master Office',
         'roles' => 'CRM,SCM,PQP,HRL,FIN,ITC,SYS',
         'perm' => ['MASTER.OFFICE_VIEW', 'MASTER.VIEW']],
        ['key' => 'mh_master_user',
         'url' => '{base}/master/master_user.php',
         'icon' => rmi_icon('users'), 'label' => 'PIC Customers (eksternal)',
         'roles' => 'CRM,MPR,ITC,SYS',
         'perm' => ['MASTER.PIC_CUSTOMER_VIEW', 'MASTER.VIEW']],
        ['key' => 'mh_master_emailcompany',
         'url' => '{base}/master/master_emailcompany.php',
         'icon' => rmi_icon('inbox'), 'label' => 'Master Email Company',
         'roles' => 'ITC,SYS',
         'perm' => ['MASTER.EMAIL_COMPANY_VIEW', 'MASTER.VIEW']],
        ['key' => 'mh_master_export_customers',
         'url' => '{base}/master/master_export_customers.php',
         'icon' => rmi_icon('outbox'), 'label' => 'Export Customers',
         'roles' => 'CRM,ITC,SYS',
         'perm' => ['MASTER.CUSTOMER_EXPORT', 'MASTER.CUSTOMER_VIEW']],
        ['key' => 'mh_import_rekening_final',
         'url' => '{base}/master/import_rekening_final.php',
         'icon' => rmi_icon('inbox'), 'label' => 'Import Rekening Final',
         'roles' => 'FIN,HRL,SYS',
         'perm' => ['HRL.IMPORT_REKENING', 'MASTER.COMPANY_BANK_VIEW', 'PURCHASES.AP_PAYMENT_VIEW']],
        ['key' => 'mh_api_partner_keys',
         'url' => '{base}/master/api_partner_keys.php',
         'icon' => rmi_icon('gear'), 'label' => 'API Partner Keys',
         'roles' => 'ITC,SYS',
         'perm' => ['SYSTEM.API_PARTNER_KEYS', 'SYSTEM.CONFIG_MANAGE']],
        ['key' => 'mh_mfa_policy',
         'url' => '{base}/master/mfa_policy.php',
         'icon' => rmi_icon('warn'), 'label' => 'Security & MFA Policy',
         'roles' => 'ITC,SYS',
         'perm' => ['SYSTEM.MFA_POLICY_MANAGE', 'SYSTEM.USER_MANAGE', 'SYSTEM.CONFIG_MANAGE']],
        // Monitoring & Audit — akses dikontrol oleh permission SYSTEM.AUDIT_LOG_VIEW (+ compat) di RBAC Center.
        // Default: SYS + ITC. Dept lain bisa diberi akses dari Nav Manager + RBAC Center.
        ['key' => 'monitoring_center',
         'url' => '{base}/master/monitoring_center.php',
         'icon' => '📡', 'label' => 'Monitoring',
         'perm' => [
             'SYSTEM.AUDIT_LOG_VIEW',
             'SYSTEM.JOBS_MONITOR',
             'SYSTEM.USER_MANAGE',
             'SYSTEM.CONFIG_MANAGE',
             'MASTER.ADMIN_CENTER',
         ],
         'roles' => 'SYS,ITC'],
        ['key' => 'audit_log',
         'url' => '{base}/master/audit_logs.php',
         'icon' => rmi_icon('clipboard'), 'label' => 'Audit Log',
         'perm' => 'SYSTEM.AUDIT_LOG_VIEW',
         'roles' => 'SYS,ITC'],
    ],

    // ══════════════════════════════════════════════════════════════════════
    // BRANCH — legacy / referensi (sidebar TIDAK lagi memuat variant ini).
    // Semua dept memakai 'default' di atas agar Nav Manager mengatur satu pohon menu penuh.
    // ══════════════════════════════════════════════════════════════════════
    'branch' => [

        ['section' => 'MAIN'],
        ['key' => 'branch_home',
         'url' => '{base}/dashboards/branch/branch_dashboard.php',
         'icon' => rmi_icon('home'), 'label' => 'Branch Dashboard',
         'roles' => 'ALL'],
        ['key' => 'branch_panduan',
         'url' => '{base}/dashboards/branch/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan BRANCH',
         'roles' => 'ALL',
         'perm' => ['DASHBOARD.BRANCH_VIEW']],
        // ── ABSENSI (sama paket seperti menu default) ─────────────────────
        ['section' => 'ABSENSI'],
        ['key' => 'absensi',
         'url' => '{base}/absensi/index.php',
         'icon' => rmi_icon('home'), 'label' => 'Absensi — Beranda',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.VIEW', 'ABSENSI.CHECKIN']],
        ['key' => 'absensi_checkin',
         'url' => '{base}/absensi/checkin.php',
         'icon' => rmi_icon('target'), 'label' => 'Check-in',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.CHECKIN']],
        ['key' => 'absensi_checkout',
         'url' => '{base}/absensi/checkout.php',
         'icon' => rmi_icon('home'), 'label' => 'Check-out',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.CHECKIN']],
        ['key' => 'absensi_history',
         'url' => '{base}/absensi/history.php',
         'icon' => rmi_icon('doc'), 'label' => 'Riwayat',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.VIEW']],
        ['key' => 'absensi_request',
         'url' => '{base}/absensi/request.php',
         'icon' => rmi_icon('memo'), 'label' => 'Pengajuan',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.REQUEST', 'ABSENSI.VIEW']],
        ['key' => 'absensi_izin',
         'url' => '{base}/absensi/izin.php',
         'icon' => rmi_icon('sun'), 'label' => 'Izin / Dinas',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.REQUEST', 'ABSENSI.VIEW']],
        ['key' => 'absensi_approval',
         'url' => '{base}/absensi/approval.php',
         'icon' => rmi_icon('check'), 'label' => 'Approval',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.APPROVE']],
        ['key' => 'absensi_panduan',
         'url' => '{base}/absensi/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan Absensi',
         'roles' => 'ALL',
         'perm' => ['ABSENSI.VIEW']],
        ['section' => 'ABSENSI ADMIN'],
        ['key' => 'absensi_admin_panel',
         'url' => '{base}/absensi/admin.php',
         'icon' => rmi_icon('gear'), 'label' => 'Admin — Panel',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_USERS']],
        ['key' => 'absensi_admin_rekap',
         'url' => '{base}/absensi/admin/rekap.php',
         'icon' => rmi_icon('clipboard'), 'label' => 'Admin — Rekap',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.RECAP']],
        ['key' => 'absensi_admin_approval',
         'url' => '{base}/absensi/admin/approval.php',
         'icon' => rmi_icon('check'), 'label' => 'Admin — Approval',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.APPROVE', 'ABSENSI.VIEW']],
        ['key' => 'absensi_admin_offices',
         'url' => '{base}/absensi/admin/offices.php',
         'icon' => rmi_icon('target'), 'label' => 'Admin — Office / GeoFence',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.OFFICE_SETTINGS']],
        ['key' => 'absensi_admin_pins',
         'url' => '{base}/absensi/admin/pins.php',
         'icon' => rmi_icon('memo'), 'label' => 'Admin — PIN',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_PINS']],
        ['key' => 'absensi_admin_user_map',
         'url' => '{base}/absensi/admin/users.php',
         'icon' => rmi_icon('users'), 'label' => 'Admin — Users Mapping',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_USERS', 'ABSENSI.ADMIN_EDIT']],
        ['key' => 'absensi_admin_shifts',
         'url' => '{base}/absensi/admin/shifts.php',
         'icon' => rmi_icon('calendar'), 'label' => 'Admin — Shift',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_EDIT']],
        ['key' => 'absensi_admin_settings',
         'url' => '{base}/absensi/admin/settings.php',
         'icon' => rmi_icon('gear'), 'label' => 'Admin — Settings',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_EDIT']],
        ['key' => 'absensi_admin_broadcast',
         'url' => '{base}/absensi/admin/broadcast.php',
         'icon' => rmi_icon('zap'), 'label' => 'Admin — Broadcast',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_EDIT']],
        ['key' => 'absensi_admin_payroll_gate',
         'url' => '{base}/absensi/admin/payroll_gate.php',
         'icon' => rmi_icon('money'), 'label' => 'Admin — Payroll Gate',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_EDIT']],
        ['key' => 'absensi_kiosk',
         'url' => '{base}/absensi/kiosk.php',
         'icon' => rmi_icon('gear'), 'label' => 'Kiosk Absensi',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.CHECKIN', 'ABSENSI.VIEW']],
        ['key' => 'absensi_kiosk_poster',
         'url' => '{base}/absensi/admin/kiosk_poster.php',
         'icon' => rmi_icon('doc'), 'label' => 'Kiosk — Poster',
         'roles' => 'HRL,ITC,SYS',
         'perm' => ['ABSENSI.ADMIN_EDIT']],
        ['key' => 'chat',
         'icon' => rmi_icon('users'), 'label' => 'Internal Chat',
         'roles' => 'ALL'],
        ['key' => 'help_center_b',
         'url' => '{base}/docs/help_center.php',
         'icon' => rmi_icon('question'), 'label' => 'Help Center',
         'roles' => 'ALL'],

        ['section' => 'SALES'],
        ['key' => 'branch_do',
         'url' => '{base}/sales/sales_do.php',
         'icon' => rmi_icon('clipboard'), 'label' => 'Delivery Order',
         'roles' => 'ALL'],
        ['key' => 'branch_ct',
         'url' => '{base}/sales/sales_control_tower.php',
         'icon' => rmi_icon('tower'), 'label' => 'Control Tower',
         'roles' => 'ALL'],
        ['key' => 'branch_sales_panduan',
         'url' => '{base}/sales/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan Sales & DO',
         'roles' => 'ALL',
         'perm' => ['PANDUAN.SALES_VIEW', 'SALES.VIEW', 'DASHBOARD.SALES_VIEW']],

        ['section' => 'WQS'],
        ['key' => 'wqs_picking',
         'icon' => rmi_icon('refresh'), 'label' => 'Picking DO',
         'roles' => 'ALL'],
        ['key' => 'wqs_do_tasks',
         'icon' => rmi_icon('clipboard'), 'label' => 'WQS – Task DO',
         'roles' => 'ALL'],
        ['key' => 'scm_do_tasks',
         'icon' => rmi_icon('outbox'), 'label' => 'SCM – Task DO',
         'roles' => 'ALL'],
        ['key' => 'branch_stok',
         'url' => '{base}/stock/wqs_stock.php',
         'icon' => rmi_icon('chart'), 'label' => 'Lihat Stok',
         'roles' => 'ALL'],
        ['key' => 'branch_pr',
         'url' => '{base}/stock/wqs_pr.php',
         'icon' => rmi_icon('memo'), 'label' => 'Purchase Request',
         'roles' => 'ALL'],
        ['key' => 'branch_incoming',
         'url' => '{base}/stock/wqs_incoming.php',
         'icon' => rmi_icon('inbox'), 'label' => 'Incoming Barang',
         'roles' => 'ALL'],
        ['key' => 'wqs_stock_opname_report',
         'url' => '{base}/stock/wqs_stock_opname_report.php',
         'icon' => rmi_icon('doc'), 'label' => 'Laporan Opname',
         'roles' => 'ALL',
         'perm' => [
             'STOCK.CREATE', 'WQS.INCOMING_VIEW', 'WQS.INCOMING_CREATE', 'WQS.INCOMING_EDIT',
             'WQS.PICKING_VIEW', 'WQS.PICKING_CREATE', 'WQS.PICKING_EDIT',
         ]],
        ['key' => 'wqs_stock_adjustment',
         'url' => '{base}/stock/wqs_stock_adjustment.php',
         'icon' => rmi_icon('chart'), 'label' => 'Stock Adjustment',
         'roles' => 'ALL',
         'perm' => ['STOCK.CREATE']],

        ['section' => 'PQP'],
        ['key' => 'branch_po',
         'url' => '{base}/purchases/purchases_po.php',
         'icon' => rmi_icon('doc'), 'label' => 'Purchase Order (PO)',
         'roles' => 'ALL'],
        ['key' => 'branch_gr',
         'url' => '{base}/purchases/purchases_gr.php',
         'icon' => rmi_icon('check'), 'label' => 'Good Receipt (GR)',
         'roles' => 'ALL'],
        ['key' => 'branch_purchases_panduan',
         'url' => '{base}/purchases/panduan.php',
         'icon' => rmi_icon('books'), 'label' => 'Panduan Purchases',
         'roles' => 'ALL',
         'perm' => ['PANDUAN.PURCHASES_VIEW', 'PURCHASES.VIEW', 'DASHBOARD.PROCUREMENT_VIEW']],

        ['section' => 'HRL'],
        ['key' => 'hrl_process',
         'url' => '{base}/hrl_process/tower.php',
         'icon' => rmi_icon('refresh'), 'label' => 'HRL Process Tower',
         'roles' => 'ALL'],
        ['key' => 'hrl_tower_cuti',
         'url' => '{base}/hrl_process/tower.php?req_type=CUTI',
         'icon' => rmi_icon('sun'), 'label' => 'Cuti',
         'roles' => 'ALL',
         'hrl_tower_type' => 'CUTI'],
        ['key' => 'hrl_tower_izin',
         'url' => '{base}/hrl_process/tower.php?req_type=IZIN',
         'icon' => rmi_icon('clipboard'), 'label' => 'Izin',
         'roles' => 'ALL',
         'hrl_tower_type' => 'IZIN'],
        ['key' => 'hrl_tower_lembur',
         'url' => '{base}/hrl_process/tower.php?req_type=LEMBUR',
         'icon' => rmi_icon('calendar'), 'label' => 'Lembur',
         'roles' => 'ALL',
         'hrl_tower_type' => 'LEMBUR'],
        ['key' => 'hrl_tower_perjadin',
         'url' => '{base}/hrl_process/tower.php?req_type=PERJADIN',
         'icon' => rmi_icon('outbox'), 'label' => 'Perjadin',
         'roles' => 'ALL',
         'hrl_tower_type' => 'PERJADIN'],
        ['key' => 'hrl_tower_permintaan_karyawan',
         'url' => '{base}/hrl_process/tower.php?req_type=PERMINTAAN_KARYAWAN',
         'icon' => rmi_icon('box'), 'label' => 'Permintaan Karyawan',
         'roles' => 'ALL',
         'hrl_tower_type' => 'PERMINTAAN_KARYAWAN'],
        ['key' => 'hrl_tower_kenaikan_gaji',
         'url' => '{base}/hrl_process/tower.php?req_type=KENAIKAN_GAJI',
         'icon' => rmi_icon('money'), 'label' => 'Kenaikan Gaji',
         'roles' => 'ALL',
         'hrl_tower_type' => 'KENAIKAN_GAJI'],
        ['key' => 'hrl_tower_rekrutmen',
         'url' => '{base}/hrl_process/tower.php?req_type=REKRUTMEN',
         'icon' => rmi_icon('users'), 'label' => 'Rekrutmen',
         'roles' => 'ALL',
         'hrl_tower_type' => 'REKRUTMEN'],
    ],
];
