<?php
declare(strict_types=1);
/** Adjustment Finance manual. Hanya koreksi yang tidak berasal dari DO/GL/AP/Stok. */
require_once __DIR__ . '/../../_shared/assets.php';
require_once __DIR__ . '/../_dashboard_bootstrap.php';
require_login();
if (function_exists('auth_is_fin_manager')) { if(!auth_is_fin_manager()){http_response_code(403);exit('Hanya Manager FIN/Admin.');} }
elseif(function_exists('require_admin_critical')) require_admin_critical(); else require_role(['SYS','ADMIN','SUPERADMIN','MANAGER']);
$pdo=$GLOBALS['pdo']??null; if(!$pdo){http_response_code(500);exit('Database connection required.');}
if(!function_exists('h')){function h($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}}
function fa_money($v):string{return number_format((float)$v,0,',','.');}
function fa_actor():string{if(function_exists('auth_user')){$u=auth_user();foreach(['username','user_name','name','full_name'] as $k)if(!empty($u[$k]))return(string)$u[$k];}return(string)($_SESSION['username']??'SYSTEM');}
function fa_ensure(PDO $pdo):void{
$pdo->exec("CREATE TABLE IF NOT EXISTS kpi_adjustments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,year_no SMALLINT NOT NULL,month_no TINYINT NOT NULL,office_id BIGINT NOT NULL DEFAULT 0,adjustment_amount DECIMAL(20,2) NOT NULL DEFAULT 0,amount DECIMAL(20,2) NOT NULL DEFAULT 0,reason VARCHAR(500) NOT NULL,created_by VARCHAR(100) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_by VARCHAR(100) NULL,updated_at DATETIME NULL,KEY idx_adj_period(year_no,month_no,office_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS kpi_finance_manual_audit(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,module VARCHAR(40) NOT NULL,record_id BIGINT NULL,action VARCHAR(30) NOT NULL,period_ym CHAR(7) NULL,office_id BIGINT NULL,segment VARCHAR(40) NULL,old_amount DECIMAL(20,2) NULL,new_amount DECIMAL(20,2) NULL,reason VARCHAR(500) NULL,actor VARCHAR(100) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_fin_audit_module(module,created_at),KEY idx_fin_audit_period(period_ym,office_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$cols=[];try{$cols=$pdo->query("SHOW COLUMNS FROM kpi_adjustments")->fetchAll(PDO::FETCH_COLUMN,0);}catch(Throwable $e){}
foreach(['adjustment_amount'=>"ALTER TABLE kpi_adjustments ADD COLUMN adjustment_amount DECIMAL(20,2) NOT NULL DEFAULT 0",'amount'=>"ALTER TABLE kpi_adjustments ADD COLUMN amount DECIMAL(20,2) NOT NULL DEFAULT 0",'reason'=>"ALTER TABLE kpi_adjustments ADD COLUMN reason VARCHAR(500) NULL",'created_by'=>"ALTER TABLE kpi_adjustments ADD COLUMN created_by VARCHAR(100) NULL",'created_at'=>"ALTER TABLE kpi_adjustments ADD COLUMN created_at DATETIME NULL",'updated_by'=>"ALTER TABLE kpi_adjustments ADD COLUMN updated_by VARCHAR(100) NULL",'updated_at'=>"ALTER TABLE kpi_adjustments ADD COLUMN updated_at DATETIME NULL"]as$c=>$sql)if(!in_array($c,$cols,true))try{$pdo->exec($sql);}catch(Throwable $e){}
}
function fa_audit(PDO$pdo,string$action,?int$id,string$period,int$officeId,?float$old,?float$new,string$reason):void{$pdo->prepare("INSERT INTO kpi_finance_manual_audit(module,record_id,action,period_ym,office_id,old_amount,new_amount,reason,actor)VALUES('ADJUSTMENT',?,?,?,?,?,?,?,?)")->execute([$id,$action,$period,$officeId,$old,$new,$reason,fa_actor()]);}
fa_ensure($pdo);
$month=(int)($_GET['month']??date('m'));$year=(int)($_GET['year']??date('Y'));if($month<1||$month>12)$month=(int)date('m');if($year<2000||$year>2100)$year=(int)date('Y');$period=sprintf('%04d-%02d',$year,$month);$success='';$error='';
$offices=[];$ids=[];try{$st=$pdo->query("SELECT id,office_code,office_name FROM master_office WHERE COALESCE(is_active,1)=1 ORDER BY office_name");while($r=$st->fetch(PDO::FETCH_ASSOC)){$oc=strtoupper(trim((string)$r['office_code']));$offices[$oc]=(string)($r['office_name']?:$oc);$ids[$oc]=(int)$r['id'];}}catch(Throwable$e){}
try{if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){if(function_exists('require_post'))require_post();if(function_exists('verify_csrf'))verify_csrf((string)($_POST['csrf_token']??''));$action=(string)($_POST['action']??'');$pMonth=(int)($_POST['month_no']??$month);$pYear=(int)($_POST['year_no']??$year);$oc=strtoupper(trim((string)($_POST['office_code']??'ALL')));$oid=$oc==='ALL'?0:(int)($ids[$oc]??0);$reason=trim((string)($_POST['reason']??''));if($oc!=='ALL'&&$oid<=0)throw new RuntimeException('Office tidak valid.');if(mb_strlen($reason)<10)throw new RuntimeException('Alasan adjustment minimal 10 karakter.');$p=sprintf('%04d-%02d',$pYear,$pMonth);
if($action==='add'){$amount=(float)($_POST['amount']??0);if(abs($amount)<0.00001)throw new RuntimeException('Nilai adjustment tidak boleh nol.');$pdo->beginTransaction();$pdo->prepare("INSERT INTO kpi_adjustments(year_no,month_no,office_id,adjustment_amount,amount,reason,created_by,created_at)VALUES(?,?,?,?,?,?,?,NOW())")->execute([$pYear,$pMonth,$oid,$amount,$amount,$reason,fa_actor()]);$id=(int)$pdo->lastInsertId();fa_audit($pdo,'CREATE',$id,$p,$oid,null,$amount,$reason);$pdo->commit();$success='Adjustment tersimpan dan tercatat audit.';$month=$pMonth;$year=$pYear;$period=$p;}
elseif($action==='delete'){$id=(int)($_POST['id']??0);$pdo->beginTransaction();$st=$pdo->prepare("SELECT*FROM kpi_adjustments WHERE id=? FOR UPDATE");$st->execute([$id]);$old=$st->fetch(PDO::FETCH_ASSOC);if(!$old)throw new RuntimeException('Adjustment tidak ditemukan.');$pdo->prepare("DELETE FROM kpi_adjustments WHERE id=?")->execute([$id]);fa_audit($pdo,'DELETE',$id,sprintf('%04d-%02d',(int)$old['year_no'],(int)$old['month_no']),(int)$old['office_id'],(float)($old['adjustment_amount']??$old['amount']??0),null,$reason);$pdo->commit();$success='Adjustment dihapus; jejak audit tetap tersimpan.';}}
}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
$st=$pdo->prepare("SELECT a.*,COALESCE(o.office_code,'ALL')office_code,COALESCE(o.office_name,'Semua Office')office_name FROM kpi_adjustments a LEFT JOIN master_office o ON o.id=a.office_id WHERE a.year_no=? AND a.month_no=? ORDER BY a.id DESC");$st->execute([$year,$month]);$rows=$st->fetchAll(PDO::FETCH_ASSOC)?:[];$sum=0;foreach($rows as$r)$sum+=(float)($r['adjustment_amount']??$r['amount']??0);
$st=$pdo->prepare("SELECT a.*,COALESCE(o.office_code,'ALL')office_code FROM kpi_finance_manual_audit a LEFT JOIN master_office o ON o.id=a.office_id WHERE a.module='ADJUSTMENT' AND a.period_ym=? ORDER BY a.id DESC LIMIT 50");$st->execute([$period]);$aud=$st->fetchAll(PDO::FETCH_ASSOC)?:[];
$bp=$GLOBALS['BASE_PROJECT']??'';require_once __DIR__.'/../../_shared/rmi_layout.php';rmi_header('Finance Adjustment','dashboard',['subtitle'=>'Koreksi manual beralasan dan teraudit • '.$period,'breadcrumbs'=>[['label'=>'Finance','url'=>$bp.'/dashboards/finance/ar_ap_cash_dashboard.php'],['label'=>'Target Finance','url'=>'target_rekap.php?month='.$month.'&year='.$year],['label'=>'Adjustment']]]);
?>
<div class="container py-3" style="max-width:1200px"><div class="alert alert-info"><strong>Gunakan hanya untuk koreksi khusus.</strong> Penjualan/pencapaian normal tetap berasal dari Sales DO; biaya dari GL; hutang dari AP; stok dari WQS.</div><?php if($success):?><div class="alert alert-success"><?=h($success)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=h($error)?></div><?php endif;?>
<div class="card p-3 mb-3"><h5>Tambah Adjustment</h5><form method="post" class="row g-2 align-items-end"><input type="hidden" name="csrf_token" value="<?=h(function_exists('csrf_token')?csrf_token():'')?>"><input type="hidden" name="action" value="add"><div class="col-md-2"><label>Bulan</label><input class="form-control" type="number" name="month_no" min="1" max="12" value="<?=$month?>"></div><div class="col-md-2"><label>Tahun</label><input class="form-control" type="number" name="year_no" value="<?=$year?>"></div><div class="col-md-3"><label>Office</label><select class="form-select" name="office_code"><option value="ALL">Semua Office</option><?php foreach($offices as$oc=>$on):?><option value="<?=h($oc)?>"><?=h($on)?> (<?=h($oc)?>)</option><?php endforeach;?></select></div><div class="col-md-2"><label>Nilai (+/-)</label><input class="form-control" type="number" step="1" name="amount" required></div><div class="col-md-3"><label>Alasan</label><input class="form-control" name="reason" minlength="10" maxlength="500" required></div><div class="col-12"><button class="btn btn-primary">Simpan Adjustment</button> <a class="btn btn-outline-light" href="target_rekap.php?month=<?=$month?>&year=<?=$year?>">Target Finance</a></div></form></div>
<div class="card p-3 mb-3"><h5>Adjustment <?=$period?> — Total <?=fa_money($sum)?></h5><div class="table-responsive"><table class="table table-dark table-sm"><thead><tr><th>Office</th><th class="text-end">Nilai</th><th>Alasan</th><th>User/Waktu</th><th>Aksi</th></tr></thead><tbody><?php foreach($rows as$r):$amt=(float)($r['adjustment_amount']??$r['amount']??0);?><tr><td><?=h($r['office_name'])?> (<?=h($r['office_code'])?>)</td><td class="text-end"><?=fa_money($amt)?></td><td><?=h($r['reason'])?></td><td><?=h($r['created_by']??'-')?> • <?=h($r['created_at']??'-')?></td><td><form method="post" onsubmit="return confirm('Hapus adjustment?')"><input type="hidden" name="csrf_token" value="<?=h(function_exists('csrf_token')?csrf_token():'')?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><input class="form-control form-control-sm mb-1" name="reason" minlength="10" placeholder="Alasan hapus" required><button class="btn btn-sm btn-outline-danger">Hapus</button></form></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="5" class="text-center">Belum ada adjustment.</td></tr><?php endif;?></tbody></table></div></div>
<div class="card p-3"><h5>Audit Adjustment</h5><div class="table-responsive"><table class="table table-dark table-sm"><thead><tr><th>Waktu</th><th>Aksi</th><th>Office</th><th>Lama</th><th>Baru</th><th>Alasan</th><th>User</th></tr></thead><tbody><?php foreach($aud as$a):?><tr><td><?=h($a['created_at'])?></td><td><?=h($a['action'])?></td><td><?=h($a['office_code'])?></td><td><?=is_null($a['old_amount'])?'-':fa_money($a['old_amount'])?></td><td><?=is_null($a['new_amount'])?'-':fa_money($a['new_amount'])?></td><td><?=h($a['reason'])?></td><td><?=h($a['actor'])?></td></tr><?php endforeach;?></tbody></table></div></div></div><?php rmi_footer(); ?>
