<?php
declare(strict_types=1);
/**
 * Auto-generated — jangan edit manual. Regenerate: php tools/gen_panduan_bundle.php
 */
return [
    ['label'=>'Panduan — Fixed Asset Register','url'=>'Fixed_Asset/panduan_assets.php','route_any'=>['FIXED_ASSET.ASSET_CRUD', 'FIXED_ASSET.ASSET_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'FIXED_ASSET.ASSET_CRUD',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'FIXED_ASSET.ASSET_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'FIXED_ASSET.AUDIT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Fixed Asset Audit','url'=>'Fixed_Asset/panduan_audit.php','route_any'=>['FIXED_ASSET.AUDIT_VIEW', 'FIXED_ASSET.AUDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'FIXED_ASSET.AUDIT_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'FIXED_ASSET.AUDIT',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Depreciation Run','url'=>'Fixed_Asset/panduan_depreciation.php','route_any'=>['FIXED_ASSET.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'FIXED_ASSET.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'FIXED_ASSET.DEPRECIATION_RUN',
  'view' => 'FIXED_ASSET.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'FIXED_ASSET.AUDIT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Fixed Asset','url'=>'Fixed_Asset/panduan_index.php','route_any'=>['FIXED_ASSET.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'FIXED_ASSET.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'FIXED_ASSET.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Fixed Asset Ops','url'=>'Fixed_Asset/panduan_ops.php','route_any'=>['FIXED_ASSET.OPERATIONS', 'FIXED_ASSET.OPS_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'FIXED_ASSET.OPERATIONS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'FIXED_ASSET.OPS_EDIT',
  'view' => 'FIXED_ASSET.OPS_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Tax Annual (Aset)','url'=>'Fixed_Asset/panduan_tax_annual.php','route_any'=>['FIXED_ASSET.TAX_ANNUAL', 'FIXED_ASSET.TAX_ANNUAL_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'FIXED_ASSET.TAX_ANNUAL',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'FIXED_ASSET.TAX_ANNUAL_EDIT',
  'view' => 'FIXED_ASSET.TAX_ANNUAL_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'FIXED_ASSET.AUDIT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Admin Approval Absensi','url'=>'absensi/admin/panduan_approval.php','route_any'=>['ABSENSI.APPROVE', 'ABSENSI.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.APPROVE',
  'create' => NULL,
  'approve' => 'ABSENSI.APPROVE',
  'edit' => NULL,
  'view' => 'ABSENSI.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Admin Offices','url'=>'absensi/admin/panduan_offices.php','route_any'=>['ABSENSI.OFFICE_SETTINGS', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.OFFICE_SETTINGS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'ABSENSI.OFFICE_SETTINGS',
  'view' => 'ABSENSI.OFFICE_SETTINGS',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Payroll Gate','url'=>'absensi/admin/panduan_payroll_gate.php','route_any'=>['ABSENSI.ADMIN_EDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.ADMIN_EDIT',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'ABSENSI.ADMIN_EDIT',
  'view' => 'ABSENSI.ADMIN_EDIT',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Admin PINs','url'=>'absensi/admin/panduan_pins.php','route_any'=>['ABSENSI.ADMIN_PINS', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.ADMIN_PINS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'ABSENSI.ADMIN_PINS',
  'view' => 'ABSENSI.ADMIN_PINS',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Rekap Absensi','url'=>'absensi/admin/panduan_rekap.php','route_any'=>['ABSENSI.RECAP', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.RECAP',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'ABSENSI.RECAP',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'ABSENSI.RECAP',
  'print' => NULL,
))],
    ['label'=>'Panduan — Admin Users Absensi','url'=>'absensi/admin/panduan_users.php','route_any'=>['ABSENSI.ADMIN_USERS', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.ADMIN_USERS',
  'create' => 'ABSENSI.ADMIN_USERS',
  'approve' => NULL,
  'edit' => 'ABSENSI.ADMIN_EDIT',
  'view' => 'ABSENSI.ADMIN_USERS',
  'delete' => 'ABSENSI.ADMIN_USERS',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Admin Absensi','url'=>'absensi/panduan_admin.php','route_any'=>['ABSENSI.ADMIN_USERS', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.ADMIN_USERS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'ABSENSI.ADMIN_USERS',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Approval Request','url'=>'absensi/panduan_approval.php','route_any'=>['ABSENSI.APPROVE', 'ABSENSI.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.APPROVE',
  'create' => NULL,
  'approve' => 'ABSENSI.APPROVE',
  'edit' => NULL,
  'view' => 'ABSENSI.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Check-in','url'=>'absensi/panduan_checkin.php','route_any'=>['ABSENSI.CHECKIN', 'ABSENSI.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.CHECKIN',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'ABSENSI.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Check-out','url'=>'absensi/panduan_checkout.php','route_any'=>['ABSENSI.CHECKIN', 'ABSENSI.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.CHECKIN',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'ABSENSI.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — History Absensi','url'=>'absensi/panduan_history.php','route_any'=>['ABSENSI.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'ABSENSI.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Absensi','url'=>'absensi/panduan_index.php','route_any'=>['ABSENSI.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'ABSENSI.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Izin','url'=>'absensi/panduan_izin.php','route_any'=>['ABSENSI.REQUEST', 'ABSENSI.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.REQUEST',
  'create' => 'ABSENSI.REQUEST',
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'ABSENSI.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Request Izin','url'=>'absensi/panduan_request.php','route_any'=>['ABSENSI.REQUEST', 'ABSENSI.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'ABSENSI.REQUEST',
  'create' => 'ABSENSI.REQUEST',
  'approve' => NULL,
  'edit' => 'ABSENSI.REQUEST_EDIT',
  'view' => 'ABSENSI.VIEW',
  'delete' => 'ABSENSI.REQUEST_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Chat Admin Audit','url'=>'chat/admin/panduan_audit.php','route_any'=>['CHAT.ADMIN_SETTINGS', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'CHAT.ADMIN_SETTINGS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'CHAT.ADMIN_SETTINGS',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'CHAT.ADMIN_SETTINGS',
  'print' => NULL,
))],
    ['label'=>'Panduan — Chat Admin Channels','url'=>'chat/admin/panduan_channels.php','route_any'=>['CHAT.ADMIN_SETTINGS', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'CHAT.ADMIN_SETTINGS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'CHAT.ADMIN_SETTINGS',
  'view' => 'CHAT.ADMIN_SETTINGS',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Chat Admin Exports','url'=>'chat/panduan_admin_exports.php','route_any'=>['CHAT.ADMIN_SETTINGS', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'CHAT.ADMIN_SETTINGS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'CHAT.ADMIN_SETTINGS',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'CHAT.ADMIN_SETTINGS',
  'print' => NULL,
))],
    ['label'=>'Panduan — Chat Admin Settings','url'=>'chat/panduan_admin_settings.php','route_any'=>['CHAT.ADMIN_SETTINGS', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'CHAT.ADMIN_SETTINGS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'CHAT.ADMIN_SETTINGS',
  'view' => 'CHAT.ADMIN_SETTINGS',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Internal Chat','url'=>'chat/panduan_index.php','route_any'=>['CHAT.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'CHAT.VIEW',
  'create' => 'CHAT.VIEW',
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'CHAT.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — ACT Dashboard','url'=>'dashboards/act/panduan_act_dashboard.php','route_any'=>['DASHBOARD.ACT_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.ACT_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.ACT_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Branch Dashboard','url'=>'dashboards/branch/panduan_branch_dashboard.php','route_any'=>['DASHBOARD.BRANCH_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.BRANCH_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.BRANCH_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Rekap Hutang (AP)','url'=>'dashboards/finance/panduan_ap_rekap.php','route_any'=>['DASHBOARD.FINANCE_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.FINANCE_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.FINANCE_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Finance Dashboard','url'=>'dashboards/finance/panduan_ar_ap_cash_dashboard.php','route_any'=>['DASHBOARD.FINANCE_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.FINANCE_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.FINANCE_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Cek DO CRM Submitted','url'=>'dashboards/finance/panduan_cek_crm_submitted.php','route_any'=>['DASHBOARD.FINANCE_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.FINANCE_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.FINANCE_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Dashboard Detail','url'=>'dashboards/finance/panduan_dashboard_detail.php','route_any'=>['DASHBOARD.FINANCE_DETAIL', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.FINANCE_DETAIL',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.FINANCE_DETAIL',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Rekap GL','url'=>'dashboards/finance/panduan_gl_rekap.php','route_any'=>['DASHBOARD.FINANCE_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.FINANCE_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.FINANCE_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Rekap Sales DO','url'=>'dashboards/finance/panduan_sales_do_rekap.php','route_any'=>['DASHBOARD.FINANCE_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.FINANCE_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.FINANCE_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'SALES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Rekap Target KPI','url'=>'dashboards/finance/panduan_target_rekap.php','route_any'=>['DASHBOARD.FINANCE_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.FINANCE_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.FINANCE_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — HRL Dashboard','url'=>'dashboards/hrl/panduan_hrl_dashboard.php','route_any'=>['DASHBOARD.HRL_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.HRL_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.HRL_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — ITC Dashboard','url'=>'dashboards/itc/panduan_itc_dashboard.php','route_any'=>['DASHBOARD.ITC_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.ITC_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.ITC_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Executive Summary','url'=>'dashboards/owner/panduan_exec_summary.php','route_any'=>['DASHBOARD.OWNER_SUMMARY', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.OWNER_SUMMARY',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.OWNER_SUMMARY',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'DASHBOARD.OWNER_VIEW',
  'print' => NULL,
))],
    ['label'=>'Panduan — Dashboards','url'=>'dashboards/panduan.php','route_any'=>['DASHBOARD.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Procurement Dashboard','url'=>'dashboards/procurement/panduan_import_po_dashboard.php','route_any'=>['DASHBOARD.PROCUREMENT_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.PROCUREMENT_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.PROCUREMENT_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — QC Complaint Dashboard','url'=>'dashboards/quality/panduan_qc_complaint_dashboard.php','route_any'=>['DASHBOARD.QUALITY_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.QUALITY_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.QUALITY_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — License Docs Dashboard','url'=>'dashboards/regulatory/panduan_license_docs_dashboard.php','route_any'=>['DASHBOARD.REGULATORY_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.REGULATORY_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.REGULATORY_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Sales Dashboard','url'=>'dashboards/sales/panduan_sales_dashboard.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — SCM Dashboard','url'=>'dashboards/scm/panduan_scm_dashboard.php','route_any'=>['DASHBOARD.SCM_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.SCM_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.SCM_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — WQS Dashboard','url'=>'dashboards/warehouse/panduan_wqs_dashboard.php','route_any'=>['DASHBOARD.WAREHOUSE_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DASHBOARD.WAREHOUSE_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DASHBOARD.WAREHOUSE_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'STOCK.AUDIT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Help Center','url'=>'docs/panduan_help_center.php','route_any'=>['DOCS.VIEW', 'DOCS.PANDUAN_VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — HRL Ack Report','url'=>'hrl/panduan_hrl_ack_report.php','route_any'=>['HRL.COMPLIANCE_EXPORT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.COMPLIANCE_EXPORT',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.COMPLIANCE_EXPORT',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'HRL.COMPLIANCE_EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — HRL Doc View','url'=>'hrl/panduan_hrl_doc_view.php','route_any'=>['HRL.DOC_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.DOC_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.DOC_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — HRL Docs','url'=>'hrl/panduan_hrl_docs.php','route_any'=>['HRL.DOC_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.DOC_VIEW',
  'create' => 'HRL.DOC_CREATE',
  'approve' => NULL,
  'edit' => 'HRL.DOC_EDIT',
  'view' => 'HRL.DOC_VIEW',
  'delete' => 'HRL.DOC_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — HRL Proses','url'=>'hrl/panduan_hrl_proses.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — HRL Tower','url'=>'hrl/panduan_hrl_tower.php','route_any'=>['HRL.PROCESS_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.PROCESS_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.PROCESS_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — HRL (Docs)','url'=>'hrl/panduan_index.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — HRL Process','url'=>'hrl_process/panduan_index.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — My PIN','url'=>'hrl_process/panduan_my_pin.php','route_any'=>['HRL.PROCESS_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.PROCESS_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.PROCESS_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Print Request','url'=>'hrl_process/panduan_request_print.php','route_any'=>['HRL.PROCESS_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.PROCESS_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.PROCESS_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => 'HRL.PROCESS_VIEW',
))],
    ['label'=>'Panduan — Request View','url'=>'hrl_process/panduan_request_view.php','route_any'=>['HRL.PROCESS_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.PROCESS_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.PROCESS_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — HRL Process Tower','url'=>'hrl_process/panduan_tower.php','route_any'=>['HRL.PROCESS_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.PROCESS_VIEW',
  'create' => 'HRL.PROCESS_CREATE',
  'approve' => 'HRL.PROCESS_EDIT',
  'edit' => 'HRL.PROCESS_EDIT',
  'view' => 'HRL.PROCESS_VIEW',
  'delete' => 'HRL.PROCESS_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — HRL Reg Alkes','url'=>'hrl_reg_alkes/panduan_index.php','route_any'=>['HRL.REG_ALKES_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.REG_ALKES_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.REG_ALKES_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Reg Alkes','url'=>'hrl_reg_alkes/panduan_reg_alkes.php','route_any'=>['HRL.REG_ALKES_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.REG_ALKES_VIEW',
  'create' => 'HRL.REG_ALKES_CREATE',
  'approve' => NULL,
  'edit' => 'HRL.REG_ALKES_EDIT',
  'view' => 'HRL.REG_ALKES_VIEW',
  'delete' => 'HRL.REG_ALKES_DELETE',
  'import' => NULL,
  'export' => 'HRL.REG_ALKES_EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Reg Alkes Case','url'=>'hrl_reg_alkes/panduan_reg_alkes_case.php','route_any'=>['HRL.REG_ALKES_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.REG_ALKES_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.REG_ALKES_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Reg Alkes Control Tower','url'=>'hrl_reg_alkes/panduan_reg_alkes_control_tower.php','route_any'=>['HRL.REG_ALKES_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.REG_ALKES_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.REG_ALKES_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'HRL.REG_ALKES_EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Reg Alkes Expiry Check','url'=>'hrl_reg_alkes/panduan_reg_alkes_expiry_check.php','route_any'=>['HRL.REG_ALKES_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.REG_ALKES_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.REG_ALKES_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'HRL.REG_ALKES_EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Reg Alkes Export Compliance','url'=>'hrl_reg_alkes/panduan_reg_alkes_export_compliance.php','route_any'=>['HRL.COMPLIANCE_EXPORT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.COMPLIANCE_EXPORT',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.COMPLIANCE_EXPORT',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'HRL.COMPLIANCE_EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Reg Alkes SKU by NIE','url'=>'hrl_reg_alkes/panduan_reg_alkes_sku_by_nie.php','route_any'=>['HRL.REG_ALKES_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'HRL.REG_ALKES_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'HRL.REG_ALKES_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — KPI Center','url'=>'kpi/panduan_index.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — KPI Daily Dashboard','url'=>'kpi/panduan_kpi_dashboard_daily.php','route_any'=>['KPI.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'KPI.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'KPI.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'KPI.DO_AUDIT',
  'print' => NULL,
))],
    ['label'=>'Panduan — KPI Monthly Dashboard','url'=>'kpi/panduan_kpi_dashboard_monthly.php','route_any'=>['KPI.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'KPI.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'KPI.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'KPI.DO_AUDIT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Account Readiness','url'=>'master/panduan_account_readiness.php','route_any'=>['SYSTEM.ACCOUNT_READINESS', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SYSTEM.ACCOUNT_READINESS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'SYSTEM.ACCOUNT_READINESS',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Rekening Perusahaan','url'=>'master/panduan_company_bank_accounts.php','route_any'=>['MASTER.COMPANY_BANK_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.COMPANY_BANK_VIEW',
  'create' => 'MASTER.COMPANY_BANK_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.COMPANY_BANK_EDIT',
  'view' => 'MASTER.COMPANY_BANK_VIEW',
  'delete' => 'MASTER.COMPANY_BANK_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Data','url'=>'master/panduan_index.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Customer','url'=>'master/panduan_master_customers.php','route_any'=>['MASTER.CUSTOMER_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.CUSTOMER_VIEW',
  'create' => 'MASTER.CUSTOMER_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.CUSTOMER_EDIT',
  'view' => 'MASTER.CUSTOMER_VIEW',
  'delete' => 'MASTER.CUSTOMER_DELETE',
  'import' => 'MASTER.IMPORT_CUSTOMERS',
  'export' => 'MASTER.CUSTOMER_EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Data (Quick Links)','url'=>'master/panduan_master_data.php','route_any'=>['MASTER.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'MASTER.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Departemen','url'=>'master/panduan_master_departements.php','route_any'=>['MASTER.DEPARTMENT_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.DEPARTMENT_VIEW',
  'create' => 'MASTER.DEPARTMENT_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.DEPARTMENT_EDIT',
  'view' => 'MASTER.DEPARTMENT_VIEW',
  'delete' => 'MASTER.DEPARTMENT_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Karyawan','url'=>'master/panduan_master_employees.php','route_any'=>['MASTER.EMPLOYEE_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.EMPLOYEE_VIEW',
  'create' => 'MASTER.EMPLOYEE_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.EMPLOYEE_EDIT',
  'view' => 'MASTER.EMPLOYEE_VIEW',
  'delete' => 'MASTER.EMPLOYEE_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Import Customer','url'=>'master/panduan_master_import_customers.php','route_any'=>['MASTER.IMPORT_CUSTOMERS', 'MASTER.CUSTOMER_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.IMPORT_CUSTOMERS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'MASTER.CUSTOMER_VIEW',
  'delete' => NULL,
  'import' => 'MASTER.IMPORT_CUSTOMERS',
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Import Produk','url'=>'master/panduan_master_import_products.php','route_any'=>['MASTER.IMPORT_PRODUCTS', 'MASTER.PRODUCT_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.IMPORT_PRODUCTS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'MASTER.PRODUCT_VIEW',
  'delete' => NULL,
  'import' => 'MASTER.IMPORT_PRODUCTS',
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Import Vendor','url'=>'master/panduan_master_import_vendors.php','route_any'=>['MASTER.IMPORT_VENDORS', 'MASTER.VENDOR_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.IMPORT_VENDORS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'MASTER.VENDOR_VIEW',
  'delete' => NULL,
  'import' => 'MASTER.IMPORT_VENDORS',
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Manufacture','url'=>'master/panduan_master_manufactures.php','route_any'=>['MASTER.MANUFACTURE_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.MANUFACTURE_VIEW',
  'create' => 'MASTER.MANUFACTURE_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.MANUFACTURE_EDIT',
  'view' => 'MASTER.MANUFACTURE_VIEW',
  'delete' => 'MASTER.MANUFACTURE_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Office','url'=>'master/panduan_master_office.php','route_any'=>['MASTER.OFFICE_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.OFFICE_VIEW',
  'create' => 'MASTER.OFFICE_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.OFFICE_EDIT',
  'view' => 'MASTER.OFFICE_VIEW',
  'delete' => 'MASTER.OFFICE_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Payment Terms','url'=>'master/panduan_master_payment_terms.php','route_any'=>['MASTER.PAYMENT_TERMS_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.PAYMENT_TERMS_VIEW',
  'create' => 'MASTER.PAYMENT_TERMS_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.PAYMENT_TERMS_EDIT',
  'view' => 'MASTER.PAYMENT_TERMS_VIEW',
  'delete' => 'MASTER.PAYMENT_TERMS_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Pricelist','url'=>'master/panduan_master_pricelist.php','route_any'=>['MASTER.PRICELIST_SELL_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.PRICELIST_SELL_VIEW',
  'create' => 'MASTER.PRICELIST_SELL_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.PRICELIST_SELL_EDIT',
  'view' => 'MASTER.PRICELIST_SELL_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Pricelist Jual','url'=>'master/panduan_master_pricelist_sell.php','route_any'=>['MASTER.PRICELIST_SELL_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.PRICELIST_SELL_VIEW',
  'create' => 'MASTER.PRICELIST_SELL_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.PRICELIST_SELL_EDIT',
  'view' => 'MASTER.PRICELIST_SELL_VIEW',
  'delete' => 'MASTER.PRICELIST_SELL_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Produk','url'=>'master/panduan_master_products.php','route_any'=>['MASTER.PRODUCT_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.PRODUCT_VIEW',
  'create' => 'MASTER.PRODUCT_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.PRODUCT_EDIT',
  'view' => 'MASTER.PRODUCT_VIEW',
  'delete' => 'MASTER.PRODUCT_DELETE',
  'import' => 'MASTER.IMPORT_PRODUCTS',
  'export' => NULL,
  'print' => 'MASTER.PRODUCT_VIEW',
))],
    ['label'=>'Panduan — Master System Login','url'=>'master/panduan_master_system_login.php','route_any'=>['SYSTEM.USER_MANAGE', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SYSTEM.USER_MANAGE',
  'create' => 'SYSTEM.USER_MANAGE',
  'approve' => NULL,
  'edit' => 'SYSTEM.USER_MANAGE',
  'view' => 'SYSTEM.USER_MANAGE',
  'delete' => 'SYSTEM.USER_MANAGE',
  'import' => NULL,
  'export' => 'SYSTEM.USER_MANAGE',
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Pajak','url'=>'master/panduan_master_tax.php','route_any'=>['MASTER.TAX_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.TAX_VIEW',
  'create' => 'MASTER.TAX_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.TAX_EDIT',
  'view' => 'MASTER.TAX_VIEW',
  'delete' => 'MASTER.TAX_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Master Vendor','url'=>'master/panduan_master_vendors.php','route_any'=>['MASTER.VENDOR_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MASTER.VENDOR_VIEW',
  'create' => 'MASTER.VENDOR_CREATE',
  'approve' => NULL,
  'edit' => 'MASTER.VENDOR_EDIT',
  'view' => 'MASTER.VENDOR_VIEW',
  'delete' => 'MASTER.VENDOR_DELETE',
  'import' => 'MASTER.IMPORT_VENDORS',
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — MPR (Marketing & Project)','url'=>'mpr/panduan_index.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — MPR Budget Approval','url'=>'mpr/panduan_mpr_budget_fin.php','route_any'=>['MPR.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MPR.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'MPR.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'MPR.PLAN_EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — MPR Dashboard','url'=>'mpr/panduan_mpr_dashboard.php','route_any'=>['MPR.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MPR.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'MPR.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — MPR Ops Daily','url'=>'mpr/panduan_mpr_ops_daily_fin.php','route_any'=>['MPR.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MPR.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'MPR.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'MPR.PLAN_EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — MPR Ops Daily Detail','url'=>'mpr/panduan_mpr_ops_daily_fin_detail.php','route_any'=>['MPR.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MPR.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'MPR.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — MPR Ops Daily Export','url'=>'mpr/panduan_mpr_ops_daily_fin_export.php','route_any'=>['MPR.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MPR.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'MPR.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'MPR.PLAN_EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — MPR Ops Daily Pay','url'=>'mpr/panduan_mpr_ops_daily_fin_pay.php','route_any'=>['MPR.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MPR.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'MPR.PLAN_EDIT',
  'view' => 'MPR.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — MPR Plan View','url'=>'mpr/panduan_mpr_plan_view.php','route_any'=>['MPR.PLAN_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MPR.PLAN_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'MPR.PLAN_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — MPR Plans','url'=>'mpr/panduan_mpr_plans.php','route_any'=>['MPR.PLAN_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'MPR.PLAN_VIEW',
  'create' => 'MPR.PLAN_CREATE',
  'approve' => 'MPR.PLAN_APPROVE',
  'edit' => 'MPR.PLAN_EDIT',
  'view' => 'MPR.PLAN_VIEW',
  'delete' => 'MPR.PLAN_DELETE',
  'import' => 'MPR.PLAN_IMPORT',
  'export' => 'MPR.PLAN_EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Payroll Audit','url'=>'payroll/panduan_audit.php','route_any'=>['PAYROLL.AUDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PAYROLL.AUDIT',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'PAYROLL.AUDIT',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PAYROLL.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Payroll','url'=>'payroll/panduan_index.php','route_any'=>['PAYROLL.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PAYROLL.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'PAYROLL.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Payroll Loans','url'=>'payroll/panduan_loans.php','route_any'=>['PAYROLL.LOANS_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PAYROLL.LOANS_VIEW',
  'create' => 'PAYROLL.LOANS_CREATE',
  'approve' => NULL,
  'edit' => 'PAYROLL.LOANS_EDIT',
  'view' => 'PAYROLL.LOANS_VIEW',
  'delete' => 'PAYROLL.LOANS_DELETE',
  'import' => NULL,
  'export' => 'PAYROLL.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Payroll Run','url'=>'payroll/panduan_payroll_run.php','route_any'=>['PAYROLL.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PAYROLL.VIEW',
  'create' => 'PAYROLL.CREATE',
  'approve' => NULL,
  'edit' => 'PAYROLL.EDIT',
  'view' => 'PAYROLL.VIEW',
  'delete' => 'PAYROLL.DELETE',
  'import' => NULL,
  'export' => 'PAYROLL.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Payroll Settings','url'=>'payroll/panduan_payroll_settings.php','route_any'=>['PAYROLL.SETTINGS', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PAYROLL.SETTINGS',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'PAYROLL.SETTINGS',
  'view' => 'PAYROLL.SETTINGS',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Payslip','url'=>'payroll/panduan_payslip.php','route_any'=>['PAYROLL.PAYSLIP_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PAYROLL.PAYSLIP_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'PAYROLL.PAYSLIP_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => 'PAYROLL.PAYSLIP_VIEW',
))],
    ['label'=>'Panduan — Salary Matrix','url'=>'payroll/panduan_salary_matrix.php','route_any'=>['PAYROLL.MATRIX_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PAYROLL.MATRIX_VIEW',
  'create' => 'PAYROLL.MATRIX_SAVE',
  'approve' => NULL,
  'edit' => 'PAYROLL.MATRIX_SAVE',
  'view' => 'PAYROLL.MATRIX_VIEW',
  'delete' => 'PAYROLL.MATRIX_DELETE',
  'import' => 'PAYROLL.MATRIX_IMPORT',
  'export' => 'PAYROLL.MATRIX_EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Bank Reconciliation','url'=>'purchases/panduan_bank_recon.php','route_any'=>['PURCHASES.AP_PAYMENT_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.AP_PAYMENT_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'PURCHASES.AP_PAYMENT_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Import Bank Statement','url'=>'purchases/panduan_bank_statement_import.php','route_any'=>['PURCHASES.AP_PAYMENT_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.AP_PAYMENT_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'PURCHASES.AP_PAYMENT_VIEW',
  'delete' => NULL,
  'import' => 'PURCHASES.AP_PAYMENT_CREATE',
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — FIN GL Auto','url'=>'purchases/panduan_fin_gl_auto.php','route_any'=>['PURCHASES.ADMIN_GL_AUTO', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.ADMIN_GL_AUTO',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'PURCHASES.ADMIN_GL_AUTO',
  'view' => 'PURCHASES.ADMIN_GL_AUTO',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — GL Reversal Approvals','url'=>'purchases/panduan_gl_reversal_approvals.php','route_any'=>['PURCHASES.GL_REVERSAL_APPROVE', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.GL_REVERSAL_APPROVE',
  'create' => NULL,
  'approve' => 'PURCHASES.GL_REVERSAL_APPROVE',
  'edit' => NULL,
  'view' => 'PURCHASES.GL_REVERSAL_APPROVE',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Purchases','url'=>'purchases/panduan_index.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — CEISA PIB List','url'=>'purchases/panduan_purchases_ceisa_pib.php','route_any'=>['PURCHASES.CEISA_VIEW', 'PURCHASES.CEISA_EDIT', 'PURCHASES.CEISA_PIB', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.CEISA_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'PURCHASES.CEISA_EDIT',
  'view' => 'PURCHASES.CEISA_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — CEISA PIB View','url'=>'purchases/panduan_purchases_ceisa_pib_view.php','route_any'=>['PURCHASES.CEISA_VIEW', 'PURCHASES.CEISA_PIB', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.CEISA_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'PURCHASES.CEISA_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Purchases Dashboard','url'=>'purchases/panduan_purchases_dashboard.php','route_any'=>['PURCHASES.VIEW', 'DASHBOARD.PROCUREMENT_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'PURCHASES.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Forwarder Invoice','url'=>'purchases/panduan_purchases_forwarder_invoice.php','route_any'=>['PURCHASES.AP_INVOICE_VIEW', 'PURCHASES.AP_INVOICE_CREATE', 'PURCHASES.AP_INVOICE_EDIT', 'PURCHASES.FORWARDING_VIEW', 'PURCHASES.FORWARDING_CREATE', 'PURCHASES.FORWARDING_EDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.FORWARDING_VIEW',
  'create' => 'PURCHASES.FORWARDING_CREATE',
  'approve' => NULL,
  'edit' => 'PURCHASES.FORWARDING_EDIT',
  'view' => 'PURCHASES.FORWARDING_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Forwarder Payment','url'=>'purchases/panduan_purchases_forwarder_payment.php','route_any'=>['PURCHASES.AP_PAYMENT_VIEW', 'PURCHASES.AP_PAYMENT_CREATE', 'PURCHASES.AP_PAYMENT_EDIT', 'PURCHASES.FORWARDING_VIEW', 'PURCHASES.FORWARDING_CREATE', 'PURCHASES.FORWARDING_EDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.FORWARDING_VIEW',
  'create' => 'PURCHASES.FORWARDING_CREATE',
  'approve' => NULL,
  'edit' => 'PURCHASES.FORWARDING_EDIT',
  'view' => 'PURCHASES.FORWARDING_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Forwarder Quotes','url'=>'purchases/panduan_purchases_forwarder_quotes.php','route_any'=>['PURCHASES.FORWARDING_VIEW', 'PURCHASES.FORWARDING_CREATE', 'PURCHASES.FORWARDING_EDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.FORWARDING_VIEW',
  'create' => 'PURCHASES.FORWARDING_CREATE',
  'approve' => NULL,
  'edit' => 'PURCHASES.FORWARDING_EDIT',
  'view' => 'PURCHASES.FORWARDING_VIEW',
  'delete' => 'PURCHASES.FORWARDING_DELETE',
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Forwarding Tasks','url'=>'purchases/panduan_purchases_forwarding_tasks.php','route_any'=>['PURCHASES.FORWARDING_VIEW', 'PURCHASES.FORWARDING_CREATE', 'PURCHASES.FORWARDING_EDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.FORWARDING_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'PURCHASES.FORWARDING_EDIT',
  'view' => 'PURCHASES.FORWARDING_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Goods Receipt','url'=>'purchases/panduan_purchases_gr.php','route_any'=>['PURCHASES.GR_VIEW', 'PURCHASES.GR_PROCESS', 'WQS.INCOMING_VIEW', 'WQS.INCOMING_CREATE', 'WQS.INCOMING_EDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.GR_VIEW',
  'create' => 'PURCHASES.GR_PROCESS',
  'approve' => NULL,
  'edit' => 'PURCHASES.GR_EDIT',
  'view' => 'PURCHASES.GR_VIEW',
  'delete' => 'PURCHASES.GR_DELETE',
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Import Control Tower','url'=>'purchases/panduan_purchases_import_control_tower.php','route_any'=>['PURCHASES.IMPORT_CONTROL', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.IMPORT_CONTROL',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'PURCHASES.IMPORT_CONTROL_EDIT',
  'view' => 'PURCHASES.IMPORT_CONTROL',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Import Control View','url'=>'purchases/panduan_purchases_import_control_view.php','route_any'=>['PURCHASES.IMPORT_CONTROL', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.IMPORT_CONTROL',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'PURCHASES.IMPORT_CONTROL',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Invoice AP','url'=>'purchases/panduan_purchases_invoice_ap.php','route_any'=>['PURCHASES.AP_INVOICE_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.AP_INVOICE_VIEW',
  'create' => 'PURCHASES.AP_INVOICE_CREATE',
  'approve' => NULL,
  'edit' => 'PURCHASES.AP_INVOICE_EDIT',
  'view' => 'PURCHASES.AP_INVOICE_VIEW',
  'delete' => 'PURCHASES.AP_INVOICE_DELETE',
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => 'PURCHASES.PO_PRINT',
))],
    ['label'=>'Panduan — Edit Invoice AP','url'=>'purchases/panduan_purchases_invoice_ap_edit.php','route_any'=>['PURCHASES.AP_INVOICE_VIEW', 'PURCHASES.AP_INVOICE_CREATE', 'PURCHASES.AP_INVOICE_EDIT', 'PURCHASES.AP_PAYMENT_VIEW', 'PURCHASES.AP_PAYMENT_CREATE', 'PURCHASES.AP_PAYMENT_EDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.AP_INVOICE_EDIT',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'PURCHASES.AP_INVOICE_EDIT',
  'view' => 'PURCHASES.AP_INVOICE_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Pembayaran AP','url'=>'purchases/panduan_purchases_payment_ap.php','route_any'=>['PURCHASES.AP_PAYMENT_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.AP_PAYMENT_VIEW',
  'create' => 'PURCHASES.AP_PAYMENT_CREATE',
  'approve' => NULL,
  'edit' => 'PURCHASES.AP_PAYMENT_EDIT',
  'view' => 'PURCHASES.AP_PAYMENT_VIEW',
  'delete' => 'PURCHASES.AP_PAYMENT_DELETE',
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Purchase Order','url'=>'purchases/panduan_purchases_po.php','route_any'=>['PURCHASES.PO_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.PO_VIEW',
  'create' => 'PURCHASES.PO_CREATE',
  'approve' => 'PURCHASES.PO_APPROVE',
  'edit' => 'PURCHASES.PO_EDIT',
  'view' => 'PURCHASES.PO_VIEW',
  'delete' => 'PURCHASES.PO_DELETE',
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => 'PURCHASES.PO_PRINT',
))],
    ['label'=>'Panduan — Print PO','url'=>'purchases/panduan_purchases_po_print.php','route_any'=>['PURCHASES.PO_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.PO_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'PURCHASES.PO_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => 'PURCHASES.PO_PRINT',
))],
    ['label'=>'Panduan — PO View','url'=>'purchases/panduan_purchases_po_view.php','route_any'=>['PURCHASES.PO_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.PO_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'PURCHASES.PO_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => 'PURCHASES.PO_PRINT',
))],
    ['label'=>'Panduan — Purchases Reports','url'=>'purchases/panduan_purchases_reports.php','route_any'=>['PURCHASES.REPORTS_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'PURCHASES.REPORTS_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'PURCHASES.REPORTS_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'PURCHASES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Stock Update from GR','url'=>'purchases/panduan_stock_update_from_gr.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — RBAC','url'=>'rbac/panduan_index.php','route_any'=>['SYSTEM.RBAC_MANAGE', 'SYSTEM.RBAC_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SYSTEM.RBAC_MANAGE',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'SYSTEM.RBAC_MANAGE',
  'view' => 'SYSTEM.RBAC_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'SYSTEM.RBAC_MANAGE',
  'print' => NULL,
))],
    ['label'=>'Panduan — RBAC Legacy','url'=>'rbac/panduan_v1_legacy.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — ACT DO Tasks','url'=>'sales/panduan_act_do_tasks.php','route_any'=>['SALES.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'SALES.EDIT',
  'view' => 'SALES.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Create Lead','url'=>'sales/panduan_crm_lead_create.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Edit Lead','url'=>'sales/panduan_crm_lead_edit.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Lead View','url'=>'sales/panduan_crm_lead_view.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — CRM Leads','url'=>'sales/panduan_crm_leads.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — FIN DO Tasks','url'=>'sales/panduan_fin_do_tasks.php','route_any'=>['SALES.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'SALES.EDIT',
  'view' => 'SALES.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Sales (CRM)','url'=>'sales/panduan_index.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — KPI DO Audit','url'=>'sales/panduan_kpi_do_audit.php','route_any'=>['SALES.AUDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.AUDIT',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'SALES.AUDIT',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'SALES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — KPI DO SLA','url'=>'sales/panduan_kpi_do_sla.php','route_any'=>['SALES.TRACKING_VIEW', 'SALES.AUDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.TRACKING_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'SALES.TRACKING_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'SALES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Sales Control Tower','url'=>'sales/panduan_sales_control_tower.php','route_any'=>['SALES.CONTROL_TOWER_VIEW', 'SALES.EDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.CONTROL_TOWER_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'SALES.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'SALES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Sales Dashboard','url'=>'sales/panduan_sales_dashboard.php','route_any'=>['SALES.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'SALES.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Sales DO','url'=>'sales/panduan_sales_do.php','route_any'=>['SALES.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.VIEW',
  'create' => 'SALES.CREATE',
  'approve' => NULL,
  'edit' => 'SALES.EDIT',
  'view' => 'SALES.VIEW',
  'delete' => 'SALES.DELETE',
  'import' => NULL,
  'export' => 'SALES.EXPORT',
  'print' => 'SALES.PRINT',
))],
    ['label'=>'Panduan — Print DO (CF)','url'=>'sales/panduan_sales_do_print_cf.php','route_any'=>['SALES.PRINT', 'SALES.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.PRINT',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'SALES.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => 'SALES.PRINT',
))],
    ['label'=>'Panduan — Sales DO Rekap','url'=>'sales/panduan_sales_do_rekap.php','route_any'=>['SALES.AUDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.AUDIT',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'SALES.AUDIT',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'SALES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Sales DO View','url'=>'sales/panduan_sales_do_view.php','route_any'=>['SALES.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'SALES.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => 'SALES.PRINT',
))],
    ['label'=>'Panduan — Sales Order','url'=>'sales/panduan_sales_order.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — SCM DO Tasks','url'=>'sales/panduan_scm_do_tasks.php','route_any'=>['SALES.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'SALES.EDIT',
  'view' => 'SALES.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — SCM Tracker Mobile','url'=>'sales/panduan_scm_tracker_mobile.php','route_any'=>['SALES.EDIT', 'MASTER.ADMIN_CENTER', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.EDIT',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'SALES.EDIT',
  'view' => 'SALES.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — SCM Tracker SOP','url'=>'sales/panduan_scm_tracker_sop.php','route_any'=>['SALES.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'SALES.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Tax Invoice','url'=>'sales/panduan_tax_invoices.php','route_any'=>['SALES.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'SALES.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'SALES.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'SALES.EXPORT',
  'print' => NULL,
))],
    ['label'=>'Panduan — WQS DO Tasks','url'=>'sales/panduan_wqs_do_tasks.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Stock (WQS)','url'=>'stock/panduan_index.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Allocation','url'=>'stock/panduan_wqs_allocation.php','route_any'=>['WQS.ALLOCATION_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'WQS.ALLOCATION_VIEW',
  'create' => 'WQS.ALLOCATION_CREATE',
  'approve' => NULL,
  'edit' => 'WQS.ALLOCATION_EDIT',
  'view' => 'WQS.ALLOCATION_VIEW',
  'delete' => 'WQS.ALLOCATION_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — WQS Incoming','url'=>'stock/panduan_wqs_incoming.php','route_any'=>['WQS.INCOMING_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'WQS.INCOMING_VIEW',
  'create' => 'WQS.INCOMING_CREATE',
  'approve' => NULL,
  'edit' => 'WQS.INCOMING_EDIT',
  'view' => 'WQS.INCOMING_VIEW',
  'delete' => 'WQS.INCOMING_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — WQS Incoming View','url'=>'stock/panduan_wqs_incoming_view.php','route_any'=>['WQS.INCOMING_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'WQS.INCOMING_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'WQS.INCOMING_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Picking','url'=>'stock/panduan_wqs_picking.php','route_any'=>['WQS.PICKING_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'WQS.PICKING_VIEW',
  'create' => 'WQS.PICKING_CREATE',
  'approve' => NULL,
  'edit' => 'WQS.PICKING_EDIT',
  'view' => 'WQS.PICKING_VIEW',
  'delete' => 'WQS.PICKING_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Picking View','url'=>'stock/panduan_wqs_picking_view.php','route_any'=>['WQS.PICKING_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'WQS.PICKING_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'WQS.PICKING_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Purchase Request (PR)','url'=>'stock/panduan_wqs_pr.php','route_any'=>['WQS.PR_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'WQS.PR_VIEW',
  'create' => 'WQS.PR_CREATE',
  'approve' => NULL,
  'edit' => 'WQS.PR_EDIT',
  'view' => 'WQS.PR_VIEW',
  'delete' => 'WQS.PR_DELETE',
  'import' => NULL,
  'export' => NULL,
  'print' => 'WQS.PR_PRINT',
))],
    ['label'=>'Panduan — Print PR','url'=>'stock/panduan_wqs_pr_print.php','route_any'=>['WQS.PR_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'WQS.PR_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'WQS.PR_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => 'WQS.PR_PRINT',
))],
    ['label'=>'Panduan — PR View','url'=>'stock/panduan_wqs_pr_view.php','route_any'=>['WQS.PR_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'WQS.PR_VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'WQS.PR_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Stock Summary','url'=>'stock/panduan_wqs_stock.php','route_any'=>['WQS.INCOMING_VIEW', 'WQS.INCOMING_CREATE', 'WQS.INCOMING_EDIT', 'STOCK.CREATE', 'WQS.PR_VIEW', 'WQS.PR_CREATE', 'WQS.PR_EDIT', 'WQS.PICKING_VIEW', 'WQS.PICKING_CREATE', 'WQS.PICKING_EDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'STOCK.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'STOCK.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'STOCK.AUDIT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Stock Adjustment','url'=>'stock/panduan_wqs_stock_adjustment.php','route_any'=>['STOCK.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'STOCK.VIEW',
  'create' => 'STOCK.CREATE',
  'approve' => NULL,
  'edit' => 'STOCK.EDIT',
  'view' => 'STOCK.VIEW',
  'delete' => 'STOCK.DELETE',
  'import' => NULL,
  'export' => 'STOCK.AUDIT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Stock Audit','url'=>'stock/panduan_wqs_stock_audit.php','route_any'=>['STOCK.AUDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'STOCK.AUDIT',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'STOCK.AUDIT',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'STOCK.AUDIT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Stock Opname','url'=>'stock/panduan_wqs_stock_opname.php','route_any'=>['STOCK.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'STOCK.VIEW',
  'create' => 'STOCK.CREATE',
  'approve' => NULL,
  'edit' => 'STOCK.EDIT',
  'view' => 'STOCK.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Stock Opname Report','url'=>'stock/panduan_wqs_stock_opname_report.php','route_any'=>['STOCK.AUDIT', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'STOCK.AUDIT',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'STOCK.AUDIT',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'STOCK.AUDIT',
  'print' => NULL,
))],
    ['label'=>'Panduan — Transfer Antar Kantor','url'=>'stock/panduan_wqs_stock_transfer.php','route_any'=>['WQS.TRANSFER_VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'WQS.TRANSFER_VIEW',
  'create' => 'WQS.TRANSFER_CREATE',
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'WQS.TRANSFER_VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Tools Control Center','url'=>'tools/ops/panduan_control_center.php','route_any'=>['DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'DOCS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => NULL,
  'view' => 'DOCS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => NULL,
  'print' => NULL,
))],
    ['label'=>'Panduan — Tools & Maintenance','url'=>'tools/panduan_index.php','route_any'=>['TOOLS.VIEW', 'DOCS.PANDUAN_VIEW', 'DOCS.VIEW'],'perms'=>_p(array (
  'access' => 'TOOLS.VIEW',
  'create' => NULL,
  'approve' => NULL,
  'edit' => 'TOOLS.BACKUP_MANAGE',
  'view' => 'TOOLS.VIEW',
  'delete' => NULL,
  'import' => NULL,
  'export' => 'TOOLS.ENTERPRISE_AUDIT_EXPORT',
  'print' => NULL,
))],
];
