<?php
/**
 * Rizqullah Mediska Indonesia — RBAC Permission Catalog (Comprehensive)
 *
 * SINGLE SOURCE OF TRUTH untuk semua permission di ERP_RMI_SOFULL.
 * Format: [perm_code, perm_name, module, description]
 *
 * Aturan:
 * - Setiap perm_code HARUS unik
 * - Sync ke DB bersifat ADDITIVE (INSERT ON DUPLICATE KEY UPDATE) — tidak menghapus DB
 * - Kode legacy/mirror underscore → kanonik: `config/rbac_legacy_merge_map.php` + migrasi **162**.
 * - Registry tambahan (ACT/FIN/SCM/…) tanpa duplikat merge map tetap di bawah.
 * - Untuk melihat total DB: SELECT COUNT(*) FROM rbac_permissions WHERE is_active=1
 */
declare(strict_types=1);

return [
    // ── SYSTEM ────────────────────────────────────────────────────────────────
    ['SYSTEM.VIEW',               'System - View',                'SYSTEM', 'Akses view halaman sistem (read-only).'],
    ['SYSTEM.USER_MANAGE',        'System - Kelola User',         'SYSTEM', 'Buat/edit/hapus user login, dept/role/office, reset password, lock/unlock.'],
    ['SYSTEM.RBAC_MANAGE',        'System - Kelola RBAC',         'SYSTEM', 'Kelola registry permission & matrix Dept+Role (RBAC Center).'],
    ['SYSTEM.RBAC_VIEW',          'System - Lihat RBAC',          'SYSTEM', 'Akses RBAC Center read-only (lihat matrix tanpa bisa simpan/sync/import).'],
    ['SYSTEM.AUDIT_LOG_VIEW',     'System - Lihat Audit Log',     'SYSTEM', 'Lihat Audit Log semua aktivitas sistem (system_audit_logs). Bisa dikonfigurasi per Dept+Role di RBAC Center.'],
    ['SYSTEM.CONFIG_MANAGE',      'System - Konfigurasi',         'SYSTEM', 'Konfigurasi global (seed KPI, office code, feature toggle).'],
    ['SYSTEM.SECURITY_VIEW',      'System - Lihat Keamanan',      'SYSTEM', 'Lihat info security/session (read-only).'],
    ['SYSTEM.MFA_POLICY_MANAGE',  'System - MFA Policy',          'SYSTEM', 'Kelola policy MFA per role/dept.'],
    ['SYSTEM.MFA_BYPASS_MANAGE',  'System - MFA Bypass',          'SYSTEM', 'Kelola MFA bypass tickets.'],
    ['SYSTEM.MFA_USER_RESET',     'System - Reset MFA User',      'SYSTEM', 'Nonaktifkan MFA user lain (halaman SYS/privileged; gate runtime auth_is_sys_tier).'],
    ['SYSTEM.JOBS_MONITOR',       'System - Jobs Monitor',        'SYSTEM', 'Monitoring worker queue, retry/run-now/cancel.'],
    ['SYSTEM.RATE_LIMIT_MANAGE',  'System - Rate Limit',          'SYSTEM', 'Konfigurasi threshold API write per scope.'],
    ['SYSTEM.ACCOUNT_READINESS',  'System - Account Readiness',   'SYSTEM', 'Cek kesiapan akun (MFA, password, dll).'],
    ['SYSTEM.API_PARTNER_KEYS',   'System - API Partner Keys',    'SYSTEM', 'Kelola API key untuk partner eksternal.'],

    // ── RBAC ──────────────────────────────────────────────────────────────────
    ['RBAC.VIEW',                 'RBAC - View',                  'RBAC', 'Akses halaman RBAC Center (read-only).'],
    ['RBAC.USER_PERMISSIONS',     'RBAC User Permissions',        'RBAC', 'Kelola override permission per user.'],
    ['RBAC.ROLE_ASSIGN',          'RBAC Role Assign',             'RBAC', 'Assign role ke user/dept.'],

    // ── MASTER ────────────────────────────────────────────────────────────────
    ['MASTER.VIEW',                   'Master - Dashboard',               'MASTER', 'Akses dashboard Master Data Center.'],
    ['MASTER.ADMIN_CENTER',           'Master - Admin Center',            'MASTER', 'Akses admin-level Master Data Center.'],
    ['MASTER.CUSTOMER_VIEW',          'Customer - Lihat',                 'MASTER', 'Lihat data pelanggan/RS/klinik.'],
    ['MASTER.CUSTOMER_CREATE',        'Customer - Tambah',                'MASTER', 'Tambah pelanggan baru.'],
    ['MASTER.CUSTOMER_EDIT',          'Customer - Edit',                  'MASTER', 'Edit data pelanggan.'],
    ['MASTER.CUSTOMER_DELETE',        'Customer - Hapus',                 'MASTER', 'Hapus data pelanggan (high risk).'],
    ['MASTER.CUSTOMER_EXPORT',        'Customer - Export',                'MASTER', 'Export daftar customer (CSV/Excel).'],
    ['MASTER.PIC_CUSTOMER_VIEW',      'PIC Customer - Lihat',             'MASTER', 'Lihat mapping PIC customer.'],
    ['MASTER.PIC_CUSTOMER_CREATE',    'PIC Customer - Tambah',            'MASTER', 'Tambah mapping PIC customer.'],
    ['MASTER.PIC_CUSTOMER_EDIT',      'PIC Customer - Edit',              'MASTER', 'Edit mapping PIC customer.'],
    ['MASTER.PIC_CUSTOMER_DELETE',    'PIC Customer - Hapus',             'MASTER', 'Hapus mapping PIC customer.'],
    ['MASTER.PRODUCT_VIEW',           'Produk - Lihat',                   'MASTER', 'Lihat daftar & detail produk.'],
    ['MASTER.PRODUCT_CREATE',         'Produk - Tambah',                  'MASTER', 'Tambah produk baru.'],
    ['MASTER.PRODUCT_EDIT',           'Produk - Edit',                    'MASTER', 'Edit data produk.'],
    ['MASTER.PRODUCT_DELETE',         'Produk - Hapus',                   'MASTER', 'Hapus data produk (high risk).'],
    ['MASTER.PRODUCT_MEDIA_UPLOAD',   'Produk - Upload Media',            'MASTER', 'Upload foto/video produk.'],
    ['MASTER.PRODUCT_PACKAGE_VIEW',   'Paket Produk - Lihat',             'MASTER', 'Lihat paket produk.'],
    ['MASTER.PRODUCT_PACKAGE_CREATE', 'Paket Produk - Tambah',            'MASTER', 'Tambah paket produk baru.'],
    ['MASTER.PRODUCT_PACKAGE_EDIT',   'Paket Produk - Edit',              'MASTER', 'Edit paket produk.'],
    ['MASTER.PRODUCT_PACKAGE_DELETE', 'Paket Produk - Hapus',             'MASTER', 'Hapus paket produk.'],
    ['MASTER.MANUFACTURE_VIEW',       'Manufacture - Lihat',              'MASTER', 'Lihat data pabrik/manufacturer.'],
    ['MASTER.MANUFACTURE_CREATE',     'Manufacture - Tambah',             'MASTER', 'Tambah data pabrik baru.'],
    ['MASTER.MANUFACTURE_EDIT',       'Manufacture - Edit',               'MASTER', 'Edit data pabrik.'],
    ['MASTER.MANUFACTURE_DELETE',     'Manufacture - Hapus',              'MASTER', 'Hapus data pabrik.'],
    ['MASTER.VENDOR_VIEW',            'Vendor - Lihat',                   'MASTER', 'Lihat data vendor.'],
    ['MASTER.VENDOR_CREATE',          'Vendor - Tambah',                  'MASTER', 'Tambah vendor baru.'],
    ['MASTER.VENDOR_EDIT',            'Vendor - Edit',                    'MASTER', 'Edit data vendor.'],
    ['MASTER.VENDOR_DELETE',          'Vendor - Hapus',                   'MASTER', 'Hapus data vendor.'],
    ['MASTER.PRICELIST_SELL_VIEW',    'Pricelist Jual - Lihat',           'MASTER', 'Lihat harga jual.'],
    ['MASTER.PRICELIST_SELL_CREATE',  'Pricelist Jual - Tambah',          'MASTER', 'Tambah harga jual baru.'],
    ['MASTER.PRICELIST_SELL_EDIT',    'Pricelist Jual - Edit',            'MASTER', 'Edit harga jual.'],
    ['MASTER.PRICELIST_SELL_DELETE',  'Pricelist Jual - Hapus',           'MASTER', 'Hapus harga jual.'],
    ['MASTER.PRICELIST_BUY_VIEW',     'Pricelist Beli - Lihat',           'MASTER', 'Lihat harga beli.'],
    ['MASTER.PRICELIST_BUY_CREATE',   'Pricelist Beli - Tambah',          'MASTER', 'Tambah harga beli baru.'],
    ['MASTER.PRICELIST_BUY_EDIT',     'Pricelist Beli - Edit',            'MASTER', 'Edit harga beli.'],
    ['MASTER.PRICELIST_BUY_DELETE',   'Pricelist Beli - Hapus',           'MASTER', 'Hapus harga beli.'],
    ['MASTER.OFFICE_VIEW',            'Office - Lihat',                   'MASTER', 'Lihat data kantor/office code.'],
    ['MASTER.OFFICE_CREATE',          'Office - Tambah',                  'MASTER', 'Tambah kantor baru.'],
    ['MASTER.OFFICE_EDIT',            'Office - Edit',                    'MASTER', 'Edit data kantor.'],
    ['MASTER.OFFICE_DELETE',          'Office - Hapus',                   'MASTER', 'Hapus data kantor.'],
    ['MASTER.TAX_VIEW',               'Pajak - Lihat',                    'MASTER', 'Lihat data pajak/PPN/withholding.'],
    ['MASTER.TAX_CREATE',             'Pajak - Tambah',                   'MASTER', 'Tambah pajak baru.'],
    ['MASTER.TAX_EDIT',               'Pajak - Edit',                     'MASTER', 'Edit data pajak.'],
    ['MASTER.TAX_DELETE',             'Pajak - Hapus',                    'MASTER', 'Hapus data pajak.'],
    ['MASTER.PAYMENT_TERMS_VIEW',     'Payment Terms - Lihat',            'MASTER', 'Lihat termin pembayaran.'],
    ['MASTER.PAYMENT_TERMS_CREATE',   'Payment Terms - Tambah',           'MASTER', 'Tambah termin pembayaran baru.'],
    ['MASTER.PAYMENT_TERMS_EDIT',     'Payment Terms - Edit',             'MASTER', 'Edit termin pembayaran.'],
    ['MASTER.PAYMENT_TERMS_DELETE',   'Payment Terms - Hapus',            'MASTER', 'Hapus termin pembayaran.'],
    ['MASTER.EMAIL_COMPANY_VIEW',     'Email Perusahaan - Lihat',         'MASTER', 'Lihat konfigurasi email perusahaan.'],
    ['MASTER.EMAIL_COMPANY_CREATE',   'Email Perusahaan - Tambah',        'MASTER', 'Tambah konfigurasi email baru.'],
    ['MASTER.EMAIL_COMPANY_EDIT',     'Email Perusahaan - Edit',          'MASTER', 'Edit konfigurasi email.'],
    ['MASTER.EMAIL_COMPANY_DELETE',   'Email Perusahaan - Hapus',         'MASTER', 'Hapus konfigurasi email.'],
    ['MASTER.EMPLOYEE_VIEW',          'Karyawan - Lihat',                 'MASTER', 'Lihat data karyawan.'],
    ['MASTER.EMPLOYEE_CREATE',        'Karyawan - Tambah',                'MASTER', 'Tambah karyawan baru.'],
    ['MASTER.EMPLOYEE_EDIT',          'Karyawan - Edit',                  'MASTER', 'Edit data karyawan.'],
    ['MASTER.EMPLOYEE_DELETE',        'Karyawan - Hapus',                 'MASTER', 'Hapus data karyawan.'],
    ['MASTER.DEPARTMENT_VIEW',        'Departemen - Lihat',               'MASTER', 'Lihat data departemen.'],
    ['MASTER.DEPARTMENT_CREATE',      'Departemen - Tambah',              'MASTER', 'Tambah departemen baru.'],
    ['MASTER.DEPARTMENT_EDIT',        'Departemen - Edit',                'MASTER', 'Edit data departemen.'],
    ['MASTER.DEPARTMENT_DELETE',      'Departemen - Hapus',               'MASTER', 'Hapus data departemen.'],
    ['MASTER.COMPANY_BANK_VIEW',      'Rekening Perusahaan - Lihat',      'MASTER', 'Lihat rekening perusahaan.'],
    ['MASTER.COMPANY_BANK_CREATE',    'Rekening Perusahaan - Tambah',     'MASTER', 'Tambah rekening perusahaan.'],
    ['MASTER.COMPANY_BANK_EDIT',      'Rekening Perusahaan - Edit',       'MASTER', 'Edit rekening perusahaan.'],
    ['MASTER.COMPANY_BANK_DELETE',    'Rekening Perusahaan - Hapus',      'MASTER', 'Hapus rekening perusahaan.'],
    ['MASTER.IMPORT_PRODUCTS',        'Produk - Import',                  'MASTER', 'Import data produk dari CSV.'],
    ['MASTER.IMPORT_CUSTOMERS',       'Customer - Import',                'MASTER', 'Import data customer dari CSV.'],
    ['MASTER.IMPORT_VENDORS',         'Vendor - Import',                  'MASTER', 'Import data vendor dari CSV.'],

    // ── MASTER CRUD aliases (dipakai master/index.php untuk UI conditional) ─────────
    ['MASTER.CUSTOMER_CRUD',      'Customer - CRUD (alias)',       'MASTER', 'Alias lama: setara CUSTOMER_VIEW + CREATE + EDIT. Gunakan granular jika bisa.'],
    ['MASTER.PRODUCT_CRUD',        'Produk - CRUD (alias)',         'MASTER', 'Alias lama: setara PRODUCT_VIEW + CREATE + EDIT.'],
    ['MASTER.VENDOR_CRUD',         'Vendor - CRUD (alias)',         'MASTER', 'Alias lama: setara VENDOR_VIEW + CREATE + EDIT.'],
    ['MASTER.EMPLOYEE_CRUD',       'Karyawan - CRUD (alias)',       'MASTER', 'Alias lama: setara EMPLOYEE_VIEW + CREATE + EDIT.'],
    ['MASTER.DEPARTMENT_CRUD',     'Departemen - CRUD (alias)',     'MASTER', 'Alias lama: setara DEPARTMENT_VIEW + EDIT.'],
    ['MASTER.COMPANY_BANK_CRUD',   'Rekening - CRUD (alias)',       'MASTER', 'Alias lama: setara COMPANY_BANK_VIEW + CREATE + EDIT.'],
    ['MASTER.PRICELIST_SELL_CRUD', 'Pricelist Jual - CRUD (alias)', 'MASTER', 'Alias lama: setara PRICELIST_SELL_VIEW + CREATE + EDIT.'],
    ['MASTER.PRICELIST_BUY_CRUD',  'Pricelist Beli - CRUD (alias)', 'MASTER', 'Alias lama: setara PRICELIST_BUY_VIEW + CREATE + EDIT.'],
    ['MASTER.MANUFACTURE_CRUD',    'Manufacture - CRUD (alias)',    'MASTER', 'Alias lama: setara MANUFACTURE_VIEW + CREATE + EDIT.'],

    // ── SALES ─────────────────────────────────────────────────────────────────
    ['SALES.VIEW',          'Sales - Lihat',            'SALES', 'Lihat dashboard, Sales Control Tower (monitoring CRM→FIN), daftar & detail DO. Berlaku untuk semua dept yang butuh akses monitor.'],
    ['SALES.CREATE',        'Sales - Buat DO',          'SALES', 'Membuat DO / transaksi sales baru.'],
    ['SALES.EDIT',          'Sales - Edit & Proses',    'SALES', 'Edit DO & proses semua tahap workflow DO.'],
    ['SALES.DELETE',        'Sales - Hapus',            'SALES', 'Hapus/batalkan DO (high risk).'],
    ['SALES.PRINT',         'Sales - Print DO',         'SALES', 'Print CF/DO.'],
    ['SALES.EXPORT',        'Sales - Export',           'SALES', 'Export data sales CSV.'],
    ['SALES.AUDIT',         'Sales - Audit & KPI',      'SALES', 'Lihat audit log DO, SLA, dan KPI penjualan.'],
    ['SALES.TRACKING_VIEW', 'Sales Tracking - View',    'SALES', 'Lihat tracking DO/shipment.'],

    // ── PANDUAN (halaman baca panduan lintas dept, assign via RBAC Center) ───
    ['PANDUAN.SALES_VIEW',     'Panduan - Sales & DO',     'PANDUAN', 'Baca sales/panduan.php tanpa hak CRUD Sales penuh.'],
    ['PANDUAN.PURCHASES_VIEW', 'Panduan - Purchases',      'PANDUAN', 'Baca purchases/panduan.php tanpa hak Purchases penuh.'],

    // ── PURCHASES ─────────────────────────────────────────────────────────────
    ['PURCHASES.VIEW',                   'Purchases - Dashboard',         'PURCHASES', 'Lihat dashboard & daftar transaksi purchases.'],
    ['PURCHASES.CREATE',                 'Purchases - Buat',              'PURCHASES', 'Membuat purchases/PO (alias).'],
    ['PURCHASES.EDIT',                   'Purchases - Edit',              'PURCHASES', 'Mengubah purchases/PO (alias).'],
    ['PURCHASES.DELETE',                 'Purchases - Hapus',             'PURCHASES', 'Menghapus purchases/PO (alias, manager only).'],
    ['PURCHASES.APPROVE',                'Purchases - Approve',           'PURCHASES', 'Approve purchases/PO (alias).'],
    ['PURCHASES.PO_VIEW',                'PO - Lihat',                   'PURCHASES', 'Lihat daftar & detail PO.'],
    ['PURCHASES.PO_CREATE',              'PO - Buat',                    'PURCHASES', 'Buat PO baru.'],
    ['PURCHASES.PO_EDIT',                'PO - Edit',                    'PURCHASES', 'Edit PO & detail item.'],
    ['PURCHASES.PO_DELETE',              'PO - Hapus',                   'PURCHASES', 'Hapus/batalkan PO (high risk).'],
    ['PURCHASES.PO_APPROVE',             'PO - Approve',                 'PURCHASES', 'Approve/lock PO.'],
    ['PURCHASES.PO_PRINT',               'PO - Print',                   'PURCHASES', 'Print PO.'],
    ['PURCHASES.GR_VIEW',                'GR - Lihat',                   'PURCHASES', 'Lihat Goods Receipt.'],
    ['PURCHASES.GR_PROCESS',             'GR - Proses/Terima',           'PURCHASES', 'Input/terima barang dari PO.'],
    ['PURCHASES.GR_EDIT',                'GR - Edit',                    'PURCHASES', 'Edit Goods Receipt.'],
    ['PURCHASES.GR_DELETE',              'GR - Hapus',                   'PURCHASES', 'Hapus/batalkan GR.'],
    ['PURCHASES.AP_INVOICE_VIEW',        'Invoice AP - Lihat',           'PURCHASES', 'Lihat Invoice AP.'],
    ['PURCHASES.AP_INVOICE_CREATE',      'Invoice AP - Buat',            'PURCHASES', 'Input Invoice AP baru.'],
    ['PURCHASES.AP_INVOICE_EDIT',        'Invoice AP - Edit',            'PURCHASES', 'Edit Invoice AP.'],
    ['PURCHASES.AP_INVOICE_DELETE',      'Invoice AP - Hapus',           'PURCHASES', 'Hapus Invoice AP.'],
    ['PURCHASES.AP_PAYMENT_VIEW',        'Payment AP - Lihat',           'PURCHASES', 'Lihat pembayaran AP.'],
    ['PURCHASES.AP_PAYMENT_CREATE',      'Payment AP - Buat',            'PURCHASES', 'Input pembayaran AP baru.'],
    ['PURCHASES.AP_PAYMENT_EDIT',        'Payment AP - Edit',            'PURCHASES', 'Edit pembayaran AP.'],
    ['PURCHASES.AP_PAYMENT_DELETE',      'Payment AP - Hapus',           'PURCHASES', 'Hapus pembayaran AP.'],
    ['PURCHASES.FORWARDING_VIEW',        'Forwarding - Lihat',           'PURCHASES', 'Lihat data forwarding/logistik.'],
    ['PURCHASES.FORWARDING_CREATE',      'Forwarding - Buat',            'PURCHASES', 'Buat data forwarder.'],
    ['PURCHASES.FORWARDING_EDIT',        'Forwarding - Edit',            'PURCHASES', 'Edit data forwarder.'],
    ['PURCHASES.FORWARDING_DELETE',      'Forwarding - Hapus',           'PURCHASES', 'Hapus data forwarder.'],
    ['PURCHASES.IMPORT_CONTROL',         'Import - Control Tower',        'PURCHASES', 'Monitoring import & compliance (control tower).'],
    ['PURCHASES.IMPORT_CONTROL_EDIT',    'Import Control - Edit',         'PURCHASES', 'Edit import control tower.'],
    ['PURCHASES.CEISA_VIEW',             'CEISA - View',                  'PURCHASES', 'Lihat dokumen CEISA/PIB.'],
    ['PURCHASES.CEISA_EDIT',             'CEISA - Edit',                  'PURCHASES', 'Edit dokumen CEISA/PIB.'],
    ['PURCHASES.CEISA_PIB',              'CEISA PIB',                     'PURCHASES', 'Entry/view dokumen PIB/CEISA (alias).'],
    ['PURCHASES.REPORTS_VIEW',           'Purchases - Laporan',           'PURCHASES', 'Lihat laporan purchases.'],
    ['PURCHASES.EXPORT',                 'Purchases - Export',            'PURCHASES', 'Export laporan/data purchases.'],
    ['PURCHASES.ADMIN_GL_AUTO',          'Purchases - GL Auto',           'PURCHASES', 'Generate jurnal otomatis (high risk).'],
    ['PURCHASES.ADMIN_STOCK_UPDATE',     'Purchases - Stock Update GR',   'PURCHASES', 'Update stock dari GR (high risk).'],
    ['PURCHASES.API_PR',                 'Purchases - API PR',            'PURCHASES', 'Endpoint API PR (internal).'],
    ['PURCHASES.AP_PAYMENT_APPROVE_POST','Payment AP - Approve/Post',     'PURCHASES', 'Approve dan post pembayaran AP (HANYA MgrFIN_BGR + SYS). Cash outflow final.'],
    ['PURCHASES.GL_REVERSAL_APPROVE',    'GL Reversal - Approve',         'PURCHASES', 'Approve GL Reversal Request (HANYA MgrFIN_BGR + SYS). High-risk dual-control.'],

    // ── FIN ───────────────────────────────────────────────────────────────────
    ['FIN.PAYMENT_APPROVE',              'FIN - Approve Pembayaran',      'FIN',       'Approval final pengeluaran kas (HANYA MgrFIN_BGR + SYS). Segregation of duty.'],

    // ── STOCK ─────────────────────────────────────────────────────────────────
    ['STOCK.VIEW',   'Stock - Lihat',        'STOCK', 'Lihat stok per office (list/summary).'],
    ['STOCK.CREATE', 'Stock - Input Opname', 'STOCK', 'Input penyesuaian/opname stok baru.'],
    ['STOCK.EDIT',   'Stock - Edit',         'STOCK', 'Edit data penyesuaian stok.'],
    ['STOCK.DELETE', 'Stock - Hapus',        'STOCK', 'Hapus penyesuaian stok (high risk).'],
    ['STOCK.AUDIT',  'Stock - Audit Log',    'STOCK', 'Lihat audit stok & movement log.'],

    // ── WQS (Warehouse) ───────────────────────────────────────────────────────
    ['WQS.VIEW',              'WQS - Dashboard',     'WQS', 'Lihat dashboard & menu WQS.'],
    ['WQS.INCOMING_VIEW',     'Incoming - Lihat',    'WQS', 'Lihat daftar penerimaan barang.'],
    ['WQS.INCOMING_CREATE',   'Incoming - Buat',     'WQS', 'Input penerimaan barang baru.'],
    ['WQS.INCOMING_EDIT',     'Incoming - Edit',     'WQS', 'Edit data incoming.'],
    ['WQS.INCOMING_DELETE',   'Incoming - Hapus',    'WQS', 'Hapus data incoming.'],
    ['WQS.PICKING_VIEW',      'Picking - Lihat',     'WQS', 'Lihat daftar picking.'],
    ['WQS.PICKING_CREATE',    'Picking - Buat',      'WQS', 'Buat picking baru untuk DO/Order.'],
    ['WQS.PICKING_EDIT',      'Picking - Edit',      'WQS', 'Edit data picking.'],
    ['WQS.PICKING_DELETE',    'Picking - Hapus',     'WQS', 'Hapus data picking.'],
    ['WQS.ALLOCATION_VIEW',   'Allocation - Lihat',  'WQS', 'Lihat alokasi stok.'],
    ['WQS.ALLOCATION_CREATE', 'Allocation - Buat',   'WQS', 'Buat alokasi stok untuk order/DO.'],
    ['WQS.ALLOCATION_EDIT',   'Allocation - Edit',   'WQS', 'Edit alokasi.'],
    ['WQS.ALLOCATION_DELETE', 'Allocation - Hapus',  'WQS', 'Hapus alokasi.'],
    ['WQS.PR_VIEW',           'PR - Lihat',          'WQS', 'Lihat daftar Purchase Request.'],
    ['WQS.PR_CREATE',         'PR - Buat',           'WQS', 'Buat Purchase Request baru.'],
    ['WQS.PR_EDIT',           'PR - Edit',           'WQS', 'Edit Purchase Request.'],
    ['WQS.PR_DELETE',         'PR - Hapus',          'WQS', 'Hapus Purchase Request.'],
    ['WQS.PR_PRINT',          'PR - Print',          'WQS', 'Print PR.'],
    ['WQS.TRANSFER_VIEW',     'Transfer - Lihat',    'WQS', 'Lihat list mutasi stok antar kantor.'],
    ['WQS.TRANSFER_CREATE',   'Transfer - Buat',     'WQS', 'Buat transfer stok antar kantor (SYS only).'],
    ['WQS.API_INCOMING_PO',   'WQS - API Incoming',  'WQS', 'API untuk load item PO ke incoming.'],

    // ── HRL ───────────────────────────────────────────────────────────────────
    ['HRL.VIEW',               'HRL - Dashboard',              'HRL', 'Akses modul HRL (dokumen, reg alkes, compliance).'],
    ['HRL.REG_ALKES_VIEW',     'Reg Alkes - Lihat',            'HRL', 'Lihat data registrasi alat kesehatan.'],
    ['HRL.REG_ALKES_CREATE',   'Reg Alkes - Tambah',           'HRL', 'Input NIE/registrasi alkes baru.'],
    ['HRL.REG_ALKES_EDIT',     'Reg Alkes - Edit',             'HRL', 'Edit data registrasi alkes.'],
    ['HRL.REG_ALKES_DELETE',   'Reg Alkes - Hapus',            'HRL', 'Hapus data registrasi alkes (high risk).'],
    ['HRL.REG_ALKES_EXPORT',   'Reg Alkes - Export',           'HRL', 'Export data reg alkes ke CSV/Excel.'],
    ['HRL.DOC_VIEW',           'Dokumen HRL - Lihat',          'HRL', 'Lihat dokumen HRL (legal, kontrak, ijin).'],
    ['HRL.DOC_CREATE',         'Dokumen HRL - Tambah',         'HRL', 'Upload/tambah dokumen HRL baru.'],
    ['HRL.DOC_EDIT',           'Dokumen HRL - Edit',           'HRL', 'Edit metadata/dokumen HRL.'],
    ['HRL.DOC_DELETE',         'Dokumen HRL - Hapus',          'HRL', 'Hapus dokumen HRL (high risk).'],
    ['HRL.COMPLIANCE_EXPORT',  'Compliance - Export',          'HRL', 'Export laporan compliance reg alkes.'],
    ['HRL.IMPORT_REKENING',    'Rekening - Import',            'HRL', 'Import rekening bank karyawan.'],
    // Kolom module HRL_PROCESS → blok terpisah di RBAC Center (permission code tetap HRL.PROCESS_*).
    ['HRL.PROCESS_VIEW',       'HRL Process - Lihat',          'HRL_PROCESS', 'Lihat list & detail request cuti/izin/dinas.'],
    ['HRL.PROCESS_CREATE',     'HRL Process - Buat',           'HRL_PROCESS', 'Buat/submit request cuti/izin/dinas.'],
    ['HRL.PROCESS_EDIT',       'HRL Process - Edit & Approve', 'HRL_PROCESS', 'Edit request & approve/reject (manager).'],
    ['HRL.PROCESS_DELETE',     'HRL Process - Hapus',          'HRL_PROCESS', 'Hapus/batalkan request (soft delete).'],
    // Per tipe pengajuan (Tower): SYS bisa atur VIEW/CREATE/EDIT/DELETE per tipe.
    ['HRL.REQ_CUTI_VIEW',                'Cuti — Lihat',                 'HRL_PROCESS', 'Lihat daftar/detail & alur approval pengajuan Cuti.'],
    ['HRL.REQ_CUTI_CREATE',              'Cuti — Buat',                  'HRL_PROCESS', 'Buat/draft/submit pengajuan Cuti.'],
    ['HRL.REQ_CUTI_EDIT',                'Cuti — Edit & approve',        'HRL_PROCESS', 'Edit draft/reject + approve/reject alur.'],
    ['HRL.REQ_CUTI_DELETE',              'Cuti — Hapus',                 'HRL_PROCESS', 'Soft delete pengajuan Cuti.'],
    ['HRL.REQ_IZIN_VIEW',                'Izin — Lihat',                 'HRL_PROCESS', 'Lihat pengajuan Izin.'],
    ['HRL.REQ_IZIN_CREATE',              'Izin — Buat',                  'HRL_PROCESS', 'Buat pengajuan Izin.'],
    ['HRL.REQ_IZIN_EDIT',                'Izin — Edit & approve',        'HRL_PROCESS', 'Edit & approve Izin.'],
    ['HRL.REQ_IZIN_DELETE',              'Izin — Hapus',                 'HRL_PROCESS', 'Hapus pengajuan Izin.'],
    ['HRL.REQ_LEMBUR_VIEW',              'Lembur — Lihat',               'HRL_PROCESS', 'Lihat pengajuan Lembur.'],
    ['HRL.REQ_LEMBUR_CREATE',            'Lembur — Buat',                'HRL_PROCESS', 'Buat pengajuan Lembur.'],
    ['HRL.REQ_LEMBUR_EDIT',              'Lembur — Edit & approve',      'HRL_PROCESS', 'Edit & approve Lembur.'],
    ['HRL.REQ_LEMBUR_DELETE',            'Lembur — Hapus',               'HRL_PROCESS', 'Hapus pengajuan Lembur.'],
    ['HRL.REQ_PERJADIN_VIEW',            'Perjadin — Lihat',             'HRL_PROCESS', 'Lihat pengajuan Perjadin (form).'],
    ['HRL.REQ_PERJADIN_CREATE',          'Perjadin — Buat',              'HRL_PROCESS', 'Buat pengajuan Perjadin.'],
    ['HRL.REQ_PERJADIN_EDIT',            'Perjadin — Edit & approve',    'HRL_PROCESS', 'Edit & approve Perjadin.'],
    ['HRL.REQ_PERJADIN_DELETE',          'Perjadin — Hapus',             'HRL_PROCESS', 'Hapus pengajuan Perjadin.'],
    ['HRL.REQ_PERMINTAAN_KARYAWAN_VIEW', 'Permintaan Karyawan — Lihat',  'HRL_PROCESS', 'Lihat pengajuan permintaan karyawan/ATK.'],
    ['HRL.REQ_PERMINTAAN_KARYAWAN_CREATE','Permintaan Karyawan — Buat',  'HRL_PROCESS', 'Buat pengajuan permintaan karyawan.'],
    ['HRL.REQ_PERMINTAAN_KARYAWAN_EDIT', 'Permintaan Karyawan — Edit',   'HRL_PROCESS', 'Edit & approve permintaan karyawan.'],
    ['HRL.REQ_PERMINTAAN_KARYAWAN_DELETE','Permintaan Karyawan — Hapus',  'HRL_PROCESS', 'Hapus pengajuan permintaan karyawan.'],
    ['HRL.REQ_KENAIKAN_GAJI_VIEW',       'Kenaikan Gaji — Lihat',        'HRL_PROCESS', 'Lihat pengajuan kenaikan gaji.'],
    ['HRL.REQ_KENAIKAN_GAJI_CREATE',     'Kenaikan Gaji — Buat',         'HRL_PROCESS', 'Buat pengajuan kenaikan gaji.'],
    ['HRL.REQ_KENAIKAN_GAJI_EDIT',       'Kenaikan Gaji — Edit & approve', 'HRL_PROCESS', 'Edit & approve kenaikan gaji.'],
    ['HRL.REQ_KENAIKAN_GAJI_DELETE',     'Kenaikan Gaji — Hapus',        'HRL_PROCESS', 'Hapus pengajuan kenaikan gaji.'],
    ['HRL.REQ_REKRUTMEN_VIEW',           'Rekrutmen — Lihat',            'HRL_PROCESS', 'Lihat pengajuan rekrutmen.'],
    ['HRL.REQ_REKRUTMEN_CREATE',         'Rekrutmen — Buat',             'HRL_PROCESS', 'Buat pengajuan rekrutmen.'],
    ['HRL.REQ_REKRUTMEN_EDIT',           'Rekrutmen — Edit & approve',   'HRL_PROCESS', 'Edit & approve rekrutmen.'],
    ['HRL.REQ_REKRUTMEN_DELETE',         'Rekrutmen — Hapus',            'HRL_PROCESS', 'Hapus pengajuan rekrutmen.'],

    // ── PAYROLL ───────────────────────────────────────────────────────────────
    ['PAYROLL.VIEW',          'Payroll - Dashboard',    'PAYROLL', 'Lihat dashboard payroll & history runs.'],
    ['PAYROLL.CREATE',        'Payroll - Generate Run', 'PAYROLL', 'Generate payroll run per periode.'],
    ['PAYROLL.EDIT',          'Payroll - Edit Run',     'PAYROLL', 'Edit item run (tunjangan/potongan/lembur).'],
    ['PAYROLL.DELETE',        'Payroll - Hapus Run',    'PAYROLL', 'Hapus payroll run (high risk).'],
    ['PAYROLL.APPROVE',       'Payroll - Post/Lock',    'PAYROLL', 'Lock/post & finalisasi payroll run.'],
    ['PAYROLL.EXPORT',        'Payroll - Export Bank',  'PAYROLL', 'Export file pembayaran bank.'],
    ['PAYROLL.SETTINGS',      'Payroll - Pengaturan',   'PAYROLL', 'Konfigurasi payroll, matrix golongan gaji.'],
    ['PAYROLL.LOANS_VIEW',    'Kasbon - Lihat',         'PAYROLL', 'Lihat data pinjaman/kasbon.'],
    ['PAYROLL.LOANS_CREATE',  'Kasbon - Tambah',        'PAYROLL', 'Input pinjaman/kasbon baru.'],
    ['PAYROLL.LOANS_EDIT',    'Kasbon - Edit',          'PAYROLL', 'Edit data pinjaman/kasbon.'],
    ['PAYROLL.LOANS_DELETE',  'Kasbon - Hapus',         'PAYROLL', 'Hapus data pinjaman/kasbon.'],
    ['PAYROLL.PAYSLIP_VIEW',  'Payslip - Lihat',        'PAYROLL', 'Lihat/print payslip.'],
    ['PAYROLL.AUDIT',         'Payroll - Audit Log',    'PAYROLL', 'Lihat audit payroll.'],

    // ── ABSENSI ───────────────────────────────────────────────────────────────
    ['ABSENSI.VIEW',           'Absensi - View Dashboard',          'ABSENSI', 'Melihat dashboard absensi.'],
    ['ABSENSI.CHECKIN',        'Absensi - Check-in/Check-out',      'ABSENSI', 'Check-in/out by photo.'],
    ['ABSENSI.REQUEST',        'Absensi - Request Izin/Sakit/Dinas','ABSENSI', 'Pengajuan izin/sakit/dinas.'],
    ['ABSENSI.REQUEST_EDIT',   'Absensi Request - Edit',             'ABSENSI', 'Edit pengajuan izin/sakit/dinas.'],
    ['ABSENSI.REQUEST_DELETE', 'Absensi Request - Delete',           'ABSENSI', 'Hapus pengajuan absensi.'],
    ['ABSENSI.APPROVE',        'Absensi - Approval',                 'ABSENSI', 'Approve request absensi.'],
    ['ABSENSI.RECAP',          'Absensi - Rekap HR',                 'ABSENSI', 'Rekap & laporan absensi.'],
    ['ABSENSI.OFFICE_SETTINGS','Absensi - Office Settings',          'ABSENSI', 'GeoFence/Office settings.'],
    ['ABSENSI.ADMIN_USERS',    'Absensi - Admin Users',              'ABSENSI', 'Kelola user absensi (mapping pin).'],
    ['ABSENSI.ADMIN_PINS',     'Absensi - Admin Pins',              'ABSENSI', 'Kelola PIN absensi.'],
    ['ABSENSI.ADMIN_EDIT',     'Absensi Admin - Edit',              'ABSENSI', 'Edit pengaturan admin absensi.'],

    // ── FIXED ASSET ───────────────────────────────────────────────────────────
    ['FIXED_ASSET.VIEW',             'Fixed Asset - Dashboard',           'FIXED_ASSET', 'Lihat dashboard fixed asset.'],
    ['FIXED_ASSET.ASSET_VIEW',       'Aset - Lihat',                      'FIXED_ASSET', 'Lihat daftar & detail aset.'],
    ['FIXED_ASSET.ASSET_CREATE',     'Aset - Tambah',                     'FIXED_ASSET', 'Input aset baru (acquisition).'],
    ['FIXED_ASSET.ASSET_EDIT',       'Aset - Edit',                       'FIXED_ASSET', 'Edit data aset.'],
    ['FIXED_ASSET.ASSET_DELETE',     'Aset - Hapus',                      'FIXED_ASSET', 'Hapus data aset (high risk).'],
    ['FIXED_ASSET.ASSET_CRUD',       'Aset - Gate CRUD halaman daftar',   'FIXED_ASSET', 'Gate halaman daftar aset (template/import/bulk; Fixed_Asset/assets.php).'],
    ['FIXED_ASSET.OPERATIONS',       'Aset - Operasional',                'FIXED_ASSET', 'Operasional aset (move, repair, dispose).'],
    ['FIXED_ASSET.OPS_VIEW',         'Aset Ops - Lihat',                  'FIXED_ASSET', 'Lihat operasional aset.'],
    ['FIXED_ASSET.OPS_EDIT',         'Aset Ops - Edit',                   'FIXED_ASSET', 'Edit operasional aset.'],
    ['FIXED_ASSET.DEPRECIATION_RUN', 'Aset - Depresiasi',                 'FIXED_ASSET', 'Hitung depresiasi periodik.'],
    ['FIXED_ASSET.TAX_ANNUAL',       'Aset - Pajak Tahunan',              'FIXED_ASSET', 'Perhitungan pajak tahunan aset.'],
    ['FIXED_ASSET.TAX_ANNUAL_VIEW',  'Aset Tax Annual - Lihat',           'FIXED_ASSET', 'Lihat perhitungan pajak tahunan.'],
    ['FIXED_ASSET.TAX_ANNUAL_EDIT',  'Aset Tax Annual - Edit',            'FIXED_ASSET', 'Edit perhitungan pajak tahunan.'],
    ['FIXED_ASSET.AUDIT',            'Aset - Audit Log',                  'FIXED_ASSET', 'Lihat audit log aset.'],
    ['FIXED_ASSET.AUDIT_VIEW',       'Aset - Gate halaman audit',         'FIXED_ASSET', 'Gate halaman audit aset (Fixed_Asset/audit.php).'],
    ['FIXED_ASSET.DISPOSAL_VIEW',    'Aset Disposal - Lihat',             'FIXED_ASSET', 'Lihat disposisi aset.'],
    ['FIXED_ASSET.DISPOSAL_EDIT',    'Aset Disposal - Edit',              'FIXED_ASSET', 'Edit disposisi aset.'],

    // ── PQP ───────────────────────────────────────────────────────────────────
    ['PQP.VIEW',           'PQP - Dashboard',  'PQP', 'Akses modul PQP (produk, quality, reg alkes).'],
    ['PQP.CREATE',         'PQP - Tambah',     'PQP', 'Buat data PQP baru.'],
    ['PQP.EDIT',           'PQP - Edit',       'PQP', 'Edit data quality/produk PQP.'],
    ['PQP.DELETE',         'PQP - Hapus',      'PQP', 'Hapus data quality PQP.'],
    ['PQP.QUALITY_VIEW',   'Quality - Lihat',  'PQP', 'Lihat data quality assurance.'],
    ['PQP.QUALITY_CREATE', 'Quality - Tambah', 'PQP', 'Input data QA baru.'],
    ['PQP.QUALITY_EDIT',   'Quality - Edit',   'PQP', 'Edit data QA.'],
    ['PQP.QUALITY_DELETE', 'Quality - Hapus',  'PQP', 'Hapus data QA (high risk).'],

    // ── MPR ───────────────────────────────────────────────────────────────────
    ['MPR.VIEW',        'MPR - Dashboard',  'MPR', 'Akses modul MPR (Marketing & Project: plans, daily ops, budget).'],
    ['MPR.PLAN_VIEW',   'Plan - Lihat',     'MPR', 'Lihat plan MPR.'],
    ['MPR.PLAN_CREATE', 'Plan - Buat',      'MPR', 'Buat plan MPR baru.'],
    ['MPR.PLAN_EDIT',   'Plan - Edit',      'MPR', 'Edit plan MPR.'],
    ['MPR.PLAN_DELETE', 'Plan - Hapus',     'MPR', 'Hapus/restore plan MPR (soft delete).'],
    ['MPR.PLAN_APPROVE','Plan - Approve',   'MPR', 'Approve/reject plan MPR.'],
    ['MPR.PLAN_IMPORT', 'Plan - Import',    'MPR', 'Import plan MPR dari CSV.'],
    ['MPR.PLAN_EXPORT', 'Plan - Export',    'MPR', 'Export report/rekap plan MPR.'],

    // ── KPI ───────────────────────────────────────────────────────────────────
    ['KPI.VIEW',            'KPI - Dashboard',       'KPI', 'Akses KPI Center & laporan KPI (RBAC: buka halaman).'],
    ['KPI.CREATE',          'KPI - Tambah',          'KPI', 'Legacy/menu. Mutasi KPI efektif hanya SYS di kode.'],
    ['KPI.EDIT',            'KPI - Edit',            'KPI', 'Legacy/menu. Bukan gate utama mutasi — level SYS (rmi_sys_gate.php).'],
    ['KPI.DELETE',          'KPI - Hapus',           'KPI', 'Legacy/menu. Hapus di app hanya SYS (kpi_can_manage).'],
    ['KPI.DO_VIEW',         'KPI DO - View',         'KPI', 'Lihat KPI DO.'],
    ['KPI.DO_AUDIT',        'KPI DO - Audit',        'KPI', 'Audit KPI DO.'],
    ['KPI.PURCHASES_VIEW',  'KPI Purchases - View',  'KPI', 'Lihat KPI purchases.'],
    ['KPI.STOCK_VIEW',      'KPI Stock - View',      'KPI', 'Lihat KPI stock.'],
    ['KPI.EMPLOYEE_VIEW',   'KPI Employee - View',   'KPI', 'Lihat KPI employee.'],
    ['KPI.OFFICE_VIEW',     'KPI Office - View',     'KPI', 'Lihat KPI office.'],

    // ── DASHBOARD ─────────────────────────────────────────────────────────────
    ['DASHBOARD.VIEW',             'Dashboard - Semua',             'DASHBOARD', 'Akses semua dashboard (override section-specific).'],
    ['DASHBOARD.SCM_VIEW',         'Dashboard SCM',                 'DASHBOARD', 'Akses SCM Dashboard.'],
    ['DASHBOARD.SALES_VIEW',       'Dashboard Sales',               'DASHBOARD', 'Akses Sales Dashboard.'],
    ['DASHBOARD.BRANCH_VIEW',      'Dashboard Branch',              'DASHBOARD', 'Akses Branch Dashboard.'],
    ['DASHBOARD.WAREHOUSE_VIEW',   'Dashboard Warehouse',           'DASHBOARD', 'Akses Warehouse/WQS Dashboard.'],
    ['DASHBOARD.FINANCE_VIEW',     'Dashboard Finance',             'DASHBOARD', 'Akses Finance Dashboard.'],
    ['DASHBOARD.PROCUREMENT_VIEW', 'Dashboard Procurement',         'DASHBOARD', 'Akses Procurement/Purchases Dashboard.'],
    ['DASHBOARD.REGULATORY_VIEW',  'Dashboard Regulatory',          'DASHBOARD', 'Akses Regulatory Dashboard.'],
    ['DASHBOARD.QUALITY_VIEW',     'Dashboard Quality',             'DASHBOARD', 'Akses Quality Dashboard.'],
    ['DASHBOARD.KPI_VIEW',         'Dashboard KPI',                 'DASHBOARD', 'Akses KPI dashboard via menu dashboard.'],
    ['DASHBOARD.HRL_VIEW',         'Dashboard HRL',                 'DASHBOARD', 'Akses HRL Dashboard.'],
    ['DASHBOARD.ITC_VIEW',         'Dashboard ITC',                 'DASHBOARD', 'Akses ITC Dashboard.'],
    ['DASHBOARD.ACT_VIEW',         'Dashboard ACT',                 'DASHBOARD', 'Akses ACT Dashboard.'],
    ['DASHBOARD.OWNER_VIEW',       'Dashboard Executive',           'DASHBOARD', 'Akses Executive Dashboard.'],
    ['DASHBOARD.FINANCE_DETAIL',   'Dashboard Finance Detail',      'DASHBOARD', 'Dashboard Detail target vs pencapaian per office.'],
    ['DASHBOARD.DETAIL_VIEW',      'Dashboard Detail - View',       'DASHBOARD', 'Lihat dashboard detail.'],
    ['DASHBOARD.OWNER_SUMMARY',    'Dashboard Executive Summary',   'DASHBOARD', 'Ringkasan bisnis untuk SYS/Manager.'],

    // ── TOOLS ─────────────────────────────────────────────────────────────────
    ['TOOLS.VIEW',                    'Tools - Dashboard',             'TOOLS', 'Akses menu Tools/Diagnostics.'],
    ['TOOLS.ENTERPRISE_AUDIT_VIEW',   'Tools - Audit View',            'TOOLS', 'Lihat hasil static scan audit keamanan/konsistensi.'],
    ['TOOLS.ENTERPRISE_AUDIT_EXPORT', 'Tools - Audit Export',          'TOOLS', 'Export audit report (CSV/JSON).'],
    ['TOOLS.BACKUP_MANAGE',           'Tools - Backup',                'TOOLS', 'Backup, restore, schedule, retention.'],
    ['TOOLS.READINESS_AUDIT',         'Tools - Readiness Audit',       'TOOLS', 'Audit kesiapan deploy & cutover.'],
    ['TOOLS.SECURITY_AUDIT',          'Tools - Security Audit',        'TOOLS', 'Static scan keamanan & konsistensi.'],
    ['TOOLS.REVIEW_KIT',              'Tools - Review Kit',            'TOOLS', 'Review kit workspace & signoff.'],
    ['TOOLS.PURCHASES_M2_APPLY',      'Tools - M2 Patch',              'TOOLS', 'Jalankan patch/repair purchases (high risk).'],
    ['TOOLS.ITC_RESET_PASSWORD',      'Tools - Reset Password',        'TOOLS', 'Reset password user (ITC support).'],
    ['TOOLS.RESTORE_VIEW',            'Tools Restore - View',          'TOOLS', 'Lihat restore/backup.'],
    ['TOOLS.RESTORE_EDIT',            'Tools Restore - Edit',          'TOOLS', 'Jalankan restore.'],
    ['TOOLS.CONTRACT_VIEW',           'Tools Contract - View',         'TOOLS', 'Lihat kontrak/agreement.'],
    ['TOOLS.RFC_VIEW',                'Tools RFC - View',              'TOOLS', 'Lihat Request for Change.'],
    ['TOOLS.RFC_APPROVE',             'Tools RFC - Approve',           'TOOLS', 'Approve Request for Change.'],
    ['TOOLS.OPS_VIEW',                'Tools Ops - View',              'TOOLS', 'Lihat operasional/ops.'],
    ['TOOLS.OPS_CONTROL_CENTER',      'Tools Ops Control Center',      'TOOLS', 'Akses Ops Control Center.'],
    ['TOOLS.COMPLIANCE_VIEW',         'Tools Compliance - View',       'TOOLS', 'Lihat compliance.'],
    ['TOOLS.COMPLIANCE_EVIDENCE',     'Tools Compliance - Evidence',   'TOOLS', 'Lihat/upload evidence compliance.'],
    ['TOOLS.RELEASE_VIEW',            'Tools Release - View',          'TOOLS', 'Lihat release/deploy.'],
    ['TOOLS.RELEASE_DEPLOY',          'Tools Release - Deploy',        'TOOLS', 'Jalankan deploy.'],
    ['TOOLS.DR_VIEW',                 'Tools DR - View',               'TOOLS', 'Lihat Disaster Recovery.'],
    ['TOOLS.DR_BACKUP',               'Tools DR - Backup',             'TOOLS', 'Jalankan DR backup.'],
    ['TOOLS.DR_RESTORE',              'Tools DR - Restore',            'TOOLS', 'Jalankan DR restore.'],

    // ── CHAT ──────────────────────────────────────────────────────────────────
    ['CHAT.VIEW',          'Chat - Lihat',    'CHAT', 'Akses Internal Chat (baca & kirim pesan).'],
    ['CHAT.ADMIN_SETTINGS','Chat - Settings', 'CHAT', 'Kelola pengaturan chat (reactions, retention, ACL, exports, audit).'],

    // ── API ───────────────────────────────────────────────────────────────────
    ['API.VIEW',            'API - View',            'API', 'Akses view API.'],
    ['API.MOBILE_ACCESS',   'API Mobile Access',     'API', 'Akses API mobile.'],
    ['API.INTERNAL_ACCESS', 'API Internal Access',   'API', 'Akses API internal.'],

    // ── WEB_ADMIN ─────────────────────────────────────────────────────────────
    ['WEB_ADMIN.VIEW',            'Web Admin - View',             'WEB_ADMIN', 'Akses Web Admin.'],
    ['WEB_ADMIN.RFC_VIEW',        'Web Admin RFC - View',         'WEB_ADMIN', 'Lihat RFC di Web Admin.'],
    ['WEB_ADMIN.RFC_APPROVE',     'Web Admin RFC - Approve',      'WEB_ADMIN', 'Approve RFC di Web Admin.'],
    ['WEB_ADMIN.OPS_VIEW',        'Web Admin Ops - View',         'WEB_ADMIN', 'Lihat ops di Web Admin.'],
    ['WEB_ADMIN.THRESHOLDS_EDIT', 'Web Admin Thresholds - Edit',  'WEB_ADMIN', 'Edit thresholds di Web Admin.'],

    // ── DOCS ──────────────────────────────────────────────────────────────────
    ['DOCS.VIEW',   'Docs - View',   'DOCS', 'Lihat dokumentasi.'],
    ['DOCS.PANDUAN_VIEW', 'Docs - Panduan halaman', 'DOCS', 'Buka halaman panduan per-fitur (tanpa akses modul utama).'],
    ['DOCS.EDIT',   'Docs - Edit',   'DOCS', 'Edit dokumentasi.'],
    ['DOCS.DELETE', 'Docs - Delete', 'DOCS', 'Hapus dokumen.'],

    // ABSENSI.CLOCK_IN, ABSENSI.CLOCK_OUT, ABSENSI.REPORT_VIEW → dihapus (duplikat)
    // Gunakan ABSENSI.CHECKIN (check-in & check-out) dan ABSENSI.RECAP (rekap laporan).

    // FIXED_ASSET granular duplikat dihapus — gunakan kode kanonik:
    // FIXED_ASSET.VIEW, FIXED_ASSET.OPERATIONS, FIXED_ASSET.DEPRECIATION_RUN,
    // FIXED_ASSET.TAX_ANNUAL, FIXED_ASSET.ASSET_VIEW/CREATE/EDIT/DELETE, FIXED_ASSET.AUDIT

    // ── MASTER (legacy alias) ─────────────────────────────────────────────────
    ['MASTER_DATA.ACCESS',           'Master Data - Akses',         'MASTER', 'Akses Master Data Center.'],
    ['MASTER_CUSTOMERS.ACCESS',      'Master Customer - Akses',     'MASTER', 'Lihat data customer.'],
    ['MASTER_CUSTOMERS.MANAGE',      'Master Customer - Kelola',    'MASTER', 'Kelola data customer.'],
    ['MASTER_CUSTOMERS.EXPORT',      'Master Customer - Export',    'MASTER', 'Export data customer.'],
    ['MASTER_DEPARTEMENTS.MANAGE',   'Master Dept - Kelola',        'MASTER', 'Kelola departemen.'],
    ['MASTER_EMAILCOMPANY.MANAGE',   'Master Email - Kelola',       'MASTER', 'Kelola email perusahaan.'],
    ['MASTER_EMPLOYEES.MANAGE',      'Master Karyawan - Kelola',    'MASTER', 'Kelola data karyawan.'],
    ['MASTER_PRODUCTS.MEDIA_VIEW',   'Master Produk - Media',       'MASTER', 'Lihat media produk.'],
    ['MASTER_PRODUCTS.PACKAGE_VIEW', 'Master Produk - Paket View',  'MASTER', 'Lihat paket produk.'],
    ['MASTER_PRODUCTS.PACKAGE_EDIT', 'Master Produk - Paket Edit',  'MASTER', 'Edit paket produk.'],
    ['MASTER_PRODUCTS.PRINT_VIEW',   'Master Produk - Print',       'MASTER', 'Lihat/print info produk.'],
    ['MASTER_SYSTEM.CONFIG_VIEW',    'Master System - Config View', 'MASTER', 'Lihat konfigurasi sistem.'],
    ['MASTER_SYSTEM.LOGIN_MANAGE',   'Master System - Login Kelola','MASTER', 'Kelola user login sistem.'],
    ['MASTER_TAX.MANAGE',            'Master Tax - Kelola',         'MASTER', 'Kelola master pajak.'],
    ['MASTER_USER.MANAGE',           'Master User - Kelola',        'MASTER', 'Kelola data user.'],
    ['MASTER_VENDORS.MANAGE',        'Master Vendor - Kelola',      'MASTER', 'Kelola data vendor.'],
    ['MASTER.PRICELIST',             'Master - Pricelist',          'MASTER', 'Kelola pricelist.'],
    ['MASTER.PRODUCTS',              'Master - Produk',             'MASTER', 'Kelola produk.'],
    ['MANUFACTURES_DOCS.ACCESS',     'Mfr Docs - Akses',            'MASTER', 'Akses dokumen manufactures.'],

    // ── SALES (alias DO / control tower) ───────────────────────────────────────
    ['SALES.DO_VIEW',             'Sales - DO View',         'SALES', 'Lihat Delivery Order.'],
    ['SALES.CONTROL_TOWER_VIEW',  'Sales - Control Tower',   'SALES', 'Akses Sales Control Tower: monitoring CRM→WQS→SCM→ACT→FIN, summary cards, milestone bar, dan filter DO. Cukup 1 dari: SALES.VIEW, SALES.EDIT, SALES.CONTROL_TOWER_VIEW.'],
    ['SALES.DO_PRINT_CF',         'Sales - DO Print CF',     'SALES', 'Print confirmation DO.'],
    ['SALES.KPI_AUDIT_VIEW',      'Sales - KPI Audit',       'SALES', 'Lihat KPI Audit DO.'],
    ['SALES.KPI_SLA_VIEW',        'Sales - KPI SLA',         'SALES', 'Lihat KPI SLA DO.'],

    // ── STOCK (granular) ──────────────────────────────────────────────────────
    ['STOCK.WQS_PICKING',         'Stock - Picking',         'STOCK', 'Proses picking DO.'],
    ['STOCK.WQS_ALLOCATION',      'Stock - Allocation',      'STOCK', 'Kelola alokasi stok.'],
    ['STOCK.WQS_STOCK_ADJUSTMENT','Stock - Adjustment',      'STOCK', 'Input stock adjustment.'],
    ['STOCK.WQS_INCOMING',        'Stock - Incoming',        'STOCK', 'Proses incoming barang.'],
    ['STOCK.OPNAME',              'Stock - Opname',          'STOCK', 'Proses stock opname.'],
    ['STOCK.TRANSFER',            'Stock - Transfer',        'STOCK', 'Transfer stok antar kantor.'],

    // ── PAYROLL (granular) ────────────────────────────────────────────────────
    ['PAYROLL.CREATE_RUN',        'Payroll - Buat Run',       'PAYROLL', 'Buat payroll run baru.'],
    ['PAYROLL.LOAN_DELETE',       'Payroll - Hapus Pinjaman', 'PAYROLL', 'Hapus data pinjaman.'],
    ['PAYROLL.LOAN_EXPORT',       'Payroll - Export Pinjaman','PAYROLL', 'Export data pinjaman.'],
    ['PAYROLL.LOAN_SAVE',         'Payroll - Simpan Pinjaman','PAYROLL', 'Input/edit pinjaman.'],
    ['PAYROLL.LOAN_STATUS',       'Payroll - Status Pinjaman','PAYROLL', 'Update status pinjaman.'],
    ['PAYROLL.MATRIX_DELETE',     'Payroll - Hapus Matrix',   'PAYROLL', 'Hapus matrix kompensasi.'],
    ['PAYROLL.MATRIX_EXPORT',     'Payroll - Export Matrix',  'PAYROLL', 'Export matrix kompensasi.'],
    ['PAYROLL.MATRIX_IMPORT',     'Payroll - Import Matrix',  'PAYROLL', 'Import matrix kompensasi.'],
    ['PAYROLL.MATRIX_SAVE',       'Payroll - Simpan Matrix',  'PAYROLL', 'Input/edit matrix kompensasi.'],
    ['PAYROLL.MATRIX_TEMPLATE',   'Payroll - Template Matrix','PAYROLL', 'Download template matrix.'],
    ['PAYROLL.MATRIX_VIEW',       'Payroll - Lihat Matrix',   'PAYROLL', 'Lihat matrix kompensasi.'],
    ['PAYROLL.RUN_RECALC_ABSENSI','Payroll - Rekalkul Absensi','PAYROLL','Rekalkul absensi di run.'],
    ['PAYROLL.RUN_SYNC_LOANS',    'Payroll - Sync Pinjaman',  'PAYROLL', 'Sync pinjaman ke run.'],
    ['PAYROLL.RUN_SYNC_MATRIX',   'Payroll - Sync Matrix',    'PAYROLL', 'Sync matrix ke run.'],
    ['PAYROLL.RUN_UPDATE_ITEM',   'Payroll - Update Item Run','PAYROLL', 'Update item di payroll run.'],
    ['PAYROLL.RUN_VIEW',          'Payroll - Lihat Run',      'PAYROLL', 'Lihat payroll run.'],
    ['PAYROLL.SETTINGS_SAVE',     'Payroll - Simpan Settings','PAYROLL', 'Simpan konfigurasi payroll.'],
    ['PAYROLL.SETTINGS_VIEW',     'Payroll - Lihat Settings', 'PAYROLL', 'Lihat konfigurasi payroll.'],

    // ── Registry tambahan (modul sempit / seed historis) ────────────────────────
    // Duplikat underscore & PAYROLL.RUN_*: rbac_legacy_merge_map.php + migrasi 162.
    ['ACT.CEISA.AUDIT_NOTE', 'ACT: Ceisa Audit Note', 'ACT', 'Catatan audit CEISA (ACT).'],
    ['ACT.CEISA.CREATE', 'ACT: Ceisa Create', 'ACT', 'Buat dokumen CEISA.'],
    ['ACT.CEISA.RESUBMIT', 'ACT: Ceisa Re-Submit', 'ACT', 'Kirim ulang CEISA.'],
    ['ACT.CEISA.SUBMIT', 'ACT: Ceisa Submit', 'ACT', 'Submit CEISA.'],
    ['ACT.CEISA.UPDATE_STATUS', 'ACT: Ceisa Update Status', 'ACT', 'Ubah status CEISA.'],
    ['ACT.CEISA.VIEW', 'ACT: Ceisa View', 'ACT', 'Lihat CEISA.'],
    ['ACT.GL.POST', 'ACT: GL Post', 'ACT', 'Posting jurnal GL (ACT).'],
    ['ACT.PERIOD.CLOSE', 'ACT: Period Close', 'ACT', 'Tutup periode akuntansi.'],
    ['ACT.REVERSAL.CREATE', 'ACT: Reversal Create', 'ACT', 'Buat reversal GL.'],

    ['FIN.AP.INVOICE.CREATE', 'FIN: AP Invoice Create', 'FIN', 'Buat invoice AP.'],
    ['FIN.AP.INVOICE.EDIT', 'FIN: AP Invoice Edit', 'FIN', 'Edit invoice AP.'],
    ['FIN.AP.INVOICE.VIEW', 'FIN: AP Invoice View', 'FIN', 'Lihat invoice AP.'],
    ['FIN.AP.PAYMENT.APPROVE', 'FIN: AP Payment Approve', 'FIN', 'Approve pembayaran AP.'],
    ['FIN.AP.PAYMENT.DRAFT', 'FIN: AP Payment Draft', 'FIN', 'Draft pembayaran AP.'],
    ['FIN.AP.PAYMENT.VIEW', 'FIN: AP Payment View', 'FIN', 'Lihat pembayaran AP.'],
    ['FIN.FORWARDER.INVOICE.CREATE', 'FIN: Forwarder Invoice Create', 'FIN', 'Invoice forwarder.'],
    ['FIN.FORWARDER.PAYMENT.APPROVE', 'FIN: Forwarder Payment Approve', 'FIN', 'Approve bayar forwarder.'],
    ['FIN.FORWARDER.PAYMENT.DRAFT', 'FIN: Forwarder Payment Draft', 'FIN', 'Draft bayar forwarder.'],
    ['FIN.PIB.PAY', 'FIN: PIB Pay', 'FIN', 'Bayar PIB.'],

    ['MASTER_WRITE', 'Master Write', 'MASTER', 'Legacy tulis master — tinjau matrix setelah migrasi 162; pertimbangkan granular MASTER.*.'],


    ['SCM.BL.FINALIZE', 'SCM Upload/Finalize BL Final', 'SCM', 'Finalisasi BL.'],
    ['SCM.BL.UPLOAD_DRAFT', 'SCM Upload BL Draft', 'SCM', 'Upload draft BL.'],
    ['SCM.BL.VIEW', 'SCM View Bill of Lading docs', 'SCM', 'Lihat dokumen BL.'],
    ['SCM.FWD.QUOTES.APPROVE', 'SCM Approve/Lock Forwarder Quote Selection', 'SCM', 'Approve quote forwarder.'],
    ['SCM.FWD.QUOTES.EDIT', 'SCM Edit Forwarder Quotes', 'SCM', 'Edit quote forwarder.'],
    ['SCM.FWD.QUOTES.VIEW', 'SCM View Forwarder Quotes', 'SCM', 'Lihat quote forwarder.'],
    ['SCM.PURCHASES.DOC.UPLOAD', 'SCM Upload Purchases Forwarder Docs (QUOTES/BL/TRACKING)', 'SCM', 'Upload dokumen forwarder.'],
    ['SCM.SHIPMENT.TRACK.UPDATE', 'SCM Update Shipment Tracking & Forwarder Fields', 'SCM', 'Update tracking kiriman.'],
    ['SCM.SHIPMENT.TRACK.VIEW', 'SCM View Shipment Tracking', 'SCM', 'Lihat tracking kiriman.'],

    ['WF.OUTBOX.VIEW', 'Workflow: View Outbox', 'WF', 'Lihat outbox workflow.'],
    ['WF.TASK.VIEW', 'Workflow: View Tasks', 'WF', 'Lihat task workflow.'],

    ['WQS.DO_TASKS', 'WQS DO Tasks (Sales)', 'WQS', 'Tugas WQS pada DO.'],
];
