<?php
declare(strict_types=1);

// Localhost-only gate for /tools
require_once __DIR__ . '/tools_remote_check.php';

require_once __DIR__ . '/../master/auth.php';
require_once __DIR__ . '/../_shared/rbac.php';
require_login();
if (function_exists('require_any_permission')) {
    require_any_permission(['TOOLS.READINESS_AUDIT', 'TOOLS.VIEW']);
} else {
    require_admin_critical();
    require_role(['SYS', 'ADMIN', 'SUPERADMIN']);
}
require_once __DIR__ . '/../_shared/rmi_layout.php';

if (!function_exists('ra_h')) {
    function ra_h(string $s): string
    {
        return htmlspecialchars($s, ENT_QUOTES, 'UTF-8');
    }
}

if (!function_exists('ra_root')) {
    function ra_root(): string
    {
        return defined('RMI_ROOT') ? (string)RMI_ROOT : (realpath(__DIR__ . '/..') ?: dirname(__DIR__));
    }
}

if (!function_exists('ra_storage')) {
    function ra_storage(string $name): string
    {
        return ra_root() . '/storage/audit/' . ltrim($name, '/');
    }
}

if (!function_exists('ra_add_check')) {
    /**
     * @param array<int,array<string,mixed>> $rows
     */
    function ra_add_check(array &$rows, string $domain, string $name, string $status, string $detail, string $evidence): void
    {
        $rows[] = [
            'domain' => $domain,
            'name' => $name,
            'status' => strtoupper($status),
            'detail' => $detail,
            'evidence' => $evidence,
        ];
    }
}

if (!function_exists('ra_table_exists')) {
    function ra_table_exists(PDO $pdo, string $table): bool
    {
        try {
            $pdo->query("SELECT 1 FROM " . $table . " LIMIT 1");
            return true;
        } catch (Throwable $e) {
            return false;
        }
    }
}

if (!function_exists('ra_file_contains')) {
    function ra_file_contains(string $path, string $needle): bool
    {
        if (!is_file($path)) return false;
        $raw = (string)@file_get_contents($path);
        return $raw !== '' && str_contains($raw, $needle);
    }
}

if (!function_exists('ra_to_markdown')) {
    /**
     * @param array<int,array<string,mixed>> $rows
     */
    function ra_to_markdown(array $rows, string $by, string $generatedAt, string $gate): string
    {
        $md = "# Readiness Audit Report (Auto)\n\n";
        $md .= "- Generated at: `{$generatedAt}`\n";
        $md .= "- Generated by: `{$by}`\n";
        $md .= "- Gate result: **{$gate}**\n\n";
        $md .= "| Domain | Check | Status | Detail | Evidence |\n";
        $md .= "|---|---|---|---|---|\n";
        foreach ($rows as $r) {
            $domain = str_replace('|', '\\|', (string)($r['domain'] ?? ''));
            $name = str_replace('|', '\\|', (string)($r['name'] ?? ''));
            $status = strtoupper((string)($r['status'] ?? 'WARN'));
            $detail = str_replace('|', '\\|', (string)($r['detail'] ?? ''));
            $evidence = str_replace('|', '\\|', (string)($r['evidence'] ?? ''));
            $md .= "| {$domain} | {$name} | {$status} | {$detail} | `{$evidence}` |\n";
        }
        return $md . "\n";
    }
}

$checks = [];
$root = ra_root();
$generatedAt = date('c');
$by = strtoupper(trim((string)($_SESSION['username'] ?? 'UNKNOWN')));

// 1) Critical files/pages for ADMIN/SUPERADMIN
$criticalFiles = [
    'master/master_system_login.php',
    'master/mfa_policy.php',
    'master/mfa_bypass.php',
    'master/jobs_monitor.php',
    'master/rate_limit_policies.php',
    'rbac/index.php',
    'chat/admin_settings.php',
    'tools/review_kit.php',
    'tools/review_kit_workspace.php',
];
foreach ($criticalFiles as $f) {
    $abs = $root . '/' . $f;
    ra_add_check(
        $checks,
        'ADMIN ACCESS',
        'File exists: ' . $f,
        is_file($abs) ? 'PASS' : 'FAIL',
        is_file($abs) ? 'Halaman tersedia.' : 'Halaman tidak ditemukan.',
        $f
    );
}

// 2) Rollout docs readiness
$rolloutDocs = [
    'ROLLOUT_24H_SOCIALIZATION_PLAN.md',
    'ROLLOUT_COMMUNICATION_TEMPLATES.md',
    'ERP_DAY1_FAQ_TROUBLESHOOT.md',
    'EXECUTIVE_BROADCAST_DAY1_ERP.md',
    'EXECUTIVE_BROADCAST_DAY1_ERP_PRINT.html',
];
foreach ($rolloutDocs as $f) {
    $abs = $root . '/' . $f;
    ra_add_check(
        $checks,
        'SOCIALIZATION',
        'Doc exists: ' . $f,
        is_file($abs) ? 'PASS' : 'WARN',
        is_file($abs) ? 'Dokumen siap dipakai.' : 'Dokumen belum ditemukan.',
        $f
    );
}

// 3) Chat migration and list consistency
$chatMigs = [
    'sql/migrations/090_internal_chat_module.sql',
    'sql/migrations/091_chat_collab_features.sql',
    'sql/migrations/092_chat_presence_thread_prefs.sql',
    'sql/migrations/093_chat_thread_acl_mentions.sql',
];
foreach ($chatMigs as $m) {
    $abs = $root . '/' . $m;
    ra_add_check(
        $checks,
        'CHAT MIGRATION',
        'Migration exists: ' . basename($m),
        is_file($abs) ? 'PASS' : 'FAIL',
        is_file($abs) ? 'File migration tersedia.' : 'File migration hilang.',
        $m
    );
}
$mList = $root . '/migrations_001_100_list.txt';
ra_add_check(
    $checks,
    'CHAT MIGRATION',
    'Migration index includes 093',
    ra_file_contains($mList, '093_chat_thread_acl_mentions.sql') ? 'PASS' : 'WARN',
    ra_file_contains($mList, '093_chat_thread_acl_mentions.sql') ? 'Index migration sudah sinkron.' : 'Index migration belum memuat 093.',
    'migrations_001_100_list.txt'
);

// 4) DB checks (best-effort)
$pdo = auth_pdo();
if ($pdo instanceof PDO) {
    // Active users with missing dept/office
    if (ra_table_exists($pdo, 'master_system_login')) {
        try {
            $sql = "SELECT COUNT(*) FROM master_system_login
                    WHERE UPPER(COALESCE(status,''))='ACTIVE'
                      AND (COALESCE(TRIM(department),'')='' OR COALESCE(TRIM(office_code),'')='')";
            $cnt = (int)$pdo->query($sql)->fetchColumn();
            ra_add_check(
                $checks,
                'ACCOUNT READINESS',
                'Active users missing dept/office',
                $cnt === 0 ? 'PASS' : 'WARN',
                $cnt === 0 ? 'Tidak ada akun bermasalah.' : ("Ditemukan {$cnt} akun aktif tanpa department/office."),
                'master_system_login'
            );
        } catch (Throwable $e) {
            ra_add_check($checks, 'ACCOUNT READINESS', 'Active users missing dept/office', 'WARN', 'Query gagal dieksekusi.', 'master_system_login');
        }
    } else {
        ra_add_check($checks, 'ACCOUNT READINESS', 'master_system_login table ready', 'WARN', 'Table tidak ditemukan di DB aktif.', 'master_system_login');
    }

    // MFA bypass expired still active
    if (ra_table_exists($pdo, 'auth_mfa_bypass_tickets')) {
        try {
            $sql = "SELECT COUNT(*) FROM auth_mfa_bypass_tickets
                    WHERE is_active=1
                      AND UPPER(COALESCE(status,''))='APPROVED'
                      AND expires_at IS NOT NULL
                      AND expires_at < NOW()";
            $cnt = (int)$pdo->query($sql)->fetchColumn();
            ra_add_check(
                $checks,
                'SECURITY',
                'Expired MFA bypass still active',
                $cnt === 0 ? 'PASS' : 'WARN',
                $cnt === 0 ? 'Tidak ada bypass kedaluwarsa yang aktif.' : ("Ditemukan {$cnt} bypass aktif yang sudah kedaluwarsa."),
                'auth_mfa_bypass_tickets'
            );
        } catch (Throwable $e) {
            ra_add_check($checks, 'SECURITY', 'Expired MFA bypass still active', 'WARN', 'Query gagal dieksekusi.', 'auth_mfa_bypass_tickets');
        }
    } else {
        ra_add_check($checks, 'SECURITY', 'auth_mfa_bypass_tickets table ready', 'WARN', 'Table bypass MFA belum tersedia.', 'auth_mfa_bypass_tickets');
    }

    // MFA policy existence
    if (ra_table_exists($pdo, 'auth_mfa_policies')) {
        try {
            $cnt = (int)$pdo->query("SELECT COUNT(*) FROM auth_mfa_policies")->fetchColumn();
            ra_add_check(
                $checks,
                'SECURITY',
                'MFA policies seeded',
                $cnt > 0 ? 'PASS' : 'WARN',
                $cnt > 0 ? ("Terdapat {$cnt} baris policy MFA.") : 'Belum ada policy MFA.',
                'auth_mfa_policies'
            );
        } catch (Throwable $e) {
            ra_add_check($checks, 'SECURITY', 'MFA policies seeded', 'WARN', 'Query gagal dieksekusi.', 'auth_mfa_policies');
        }
    } else {
        ra_add_check($checks, 'SECURITY', 'auth_mfa_policies table ready', 'WARN', 'Table policy MFA belum tersedia.', 'auth_mfa_policies');
    }
} else {
    ra_add_check($checks, 'DB', 'Database connectivity', 'FAIL', 'Koneksi DB tidak tersedia dari auth_pdo().', '_shared/db.php');
}

// summarize
$pass = count(array_filter($checks, static fn($r): bool => strtoupper((string)($r['status'] ?? '')) === 'PASS'));
$warn = count(array_filter($checks, static fn($r): bool => strtoupper((string)($r['status'] ?? '')) === 'WARN'));
$fail = count(array_filter($checks, static fn($r): bool => strtoupper((string)($r['status'] ?? '')) === 'FAIL'));
$gate = $fail > 0 ? 'NO-GO' : (($warn > 3) ? 'GO WITH CAUTION' : 'GO');

// persist report
$jsonFile = ra_storage('readiness_audit_latest.json');
$mdFile = ra_storage('readiness_audit_latest.md');
$dir = dirname($jsonFile);
if (!is_dir($dir)) {
    @mkdir($dir, 0775, true);
}
@file_put_contents($jsonFile, json_encode([
    'generated_at' => $generatedAt,
    'generated_by' => $by,
    'gate' => $gate,
    'summary' => ['pass' => $pass, 'warn' => $warn, 'fail' => $fail, 'total' => count($checks)],
    'checks' => $checks,
], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . PHP_EOL, LOCK_EX);
@file_put_contents($mdFile, ra_to_markdown($checks, $by, $generatedAt, $gate), LOCK_EX);

$base = rmi_layout_base_project();
rmi_header('Readiness Audit (Auto)', [
    'active' => 'tools',
    'subtitle' => 'Audit otomatis kesiapan akun, akses admin, migration, dan dokumen rollout.',
    'breadcrumbs' => [
        ['label' => 'Tools', 'url' => $base . '/tools/index.php'],
        'Readiness Audit',
    ],
]);
?>

<div class="row g-3 mb-3">
  <div class="col-md-3">
    <div class="rmi-card p-3 h-100">
      <div class="rmi-muted">Gate</div>
      <div class="fs-4 fw-bold"><?= ra_h($gate) ?></div>
      <div class="small rmi-muted">Generated: <?= ra_h($generatedAt) ?></div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="rmi-card p-3 h-100">
      <div class="rmi-muted">PASS</div>
      <div class="fs-4 fw-bold text-success"><?= (int)$pass ?></div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="rmi-card p-3 h-100">
      <div class="rmi-muted">WARN</div>
      <div class="fs-4 fw-bold text-warning"><?= (int)$warn ?></div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="rmi-card p-3 h-100">
      <div class="rmi-muted">FAIL</div>
      <div class="fs-4 fw-bold text-danger"><?= (int)$fail ?></div>
    </div>
  </div>
</div>

<div class="rmi-card p-3 mb-3">
  <div class="fw-semibold mb-2">Output Report</div>
  <div class="small">
    JSON: <code>storage/audit/readiness_audit_latest.json</code><br>
    Markdown: <code>storage/audit/readiness_audit_latest.md</code>
  </div>
</div>

<div class="rmi-card p-3">
  <div class="fw-semibold mb-2">Check Results</div>
  <div class="table-responsive">
    <table class="table table-sm align-middle">
      <thead>
        <tr>
          <th>Domain</th>
          <th>Check</th>
          <th>Status</th>
          <th>Detail</th>
          <th>Evidence</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($checks as $c): ?>
        <?php $st = strtoupper((string)$c['status']); ?>
        <tr>
          <td><?= ra_h((string)$c['domain']) ?></td>
          <td><?= ra_h((string)$c['name']) ?></td>
          <td>
            <?php if ($st === 'PASS'): ?>
              <span class="badge text-bg-success">PASS</span>
            <?php elseif ($st === 'FAIL'): ?>
              <span class="badge text-bg-danger">FAIL</span>
            <?php else: ?>
              <span class="badge text-bg-warning text-dark">WARN</span>
            <?php endif; ?>
          </td>
          <td><?= ra_h((string)$c['detail']) ?></td>
          <td><code><?= ra_h((string)$c['evidence']) ?></code></td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>

<?php rmi_footer(); ?>

